=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'cgi'

module Kombo
  class DefaultApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # AI Apply: Application status updated
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param ai_apply_application_status_updated_webhook_payload [AiApplyApplicationStatusUpdatedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def webhook_ai_apply_application_status_updated_webhook_payload(x_kombo_signature, ai_apply_application_status_updated_webhook_payload, opts = {})
      webhook_ai_apply_application_status_updated_webhook_payload_with_http_info(x_kombo_signature, ai_apply_application_status_updated_webhook_payload, opts)
      nil
    end

    # AI Apply: Application status updated
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param ai_apply_application_status_updated_webhook_payload [AiApplyApplicationStatusUpdatedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def webhook_ai_apply_application_status_updated_webhook_payload_with_http_info(x_kombo_signature, ai_apply_application_status_updated_webhook_payload, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.webhook_ai_apply_application_status_updated_webhook_payload ...'
      end
      # verify the required parameter 'x_kombo_signature' is set
      if @api_client.config.client_side_validation && x_kombo_signature.nil?
        fail ArgumentError, "Missing the required parameter 'x_kombo_signature' when calling DefaultApi.webhook_ai_apply_application_status_updated_webhook_payload"
      end
      # verify the required parameter 'ai_apply_application_status_updated_webhook_payload' is set
      if @api_client.config.client_side_validation && ai_apply_application_status_updated_webhook_payload.nil?
        fail ArgumentError, "Missing the required parameter 'ai_apply_application_status_updated_webhook_payload' when calling DefaultApi.webhook_ai_apply_application_status_updated_webhook_payload"
      end
      # resource path
      local_var_path = '/ai-apply-application-status-updated'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Kombo-Signature'] = x_kombo_signature

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(ai_apply_application_status_updated_webhook_payload)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.webhook_ai_apply_application_status_updated_webhook_payload",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#webhook_ai_apply_application_status_updated_webhook_payload\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # AI Apply: Job posting status updated
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param ai_apply_job_posting_status_updated_webhook_payload [AiApplyJobPostingStatusUpdatedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def webhook_ai_apply_job_posting_status_updated_webhook_payload(x_kombo_signature, ai_apply_job_posting_status_updated_webhook_payload, opts = {})
      webhook_ai_apply_job_posting_status_updated_webhook_payload_with_http_info(x_kombo_signature, ai_apply_job_posting_status_updated_webhook_payload, opts)
      nil
    end

    # AI Apply: Job posting status updated
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param ai_apply_job_posting_status_updated_webhook_payload [AiApplyJobPostingStatusUpdatedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def webhook_ai_apply_job_posting_status_updated_webhook_payload_with_http_info(x_kombo_signature, ai_apply_job_posting_status_updated_webhook_payload, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.webhook_ai_apply_job_posting_status_updated_webhook_payload ...'
      end
      # verify the required parameter 'x_kombo_signature' is set
      if @api_client.config.client_side_validation && x_kombo_signature.nil?
        fail ArgumentError, "Missing the required parameter 'x_kombo_signature' when calling DefaultApi.webhook_ai_apply_job_posting_status_updated_webhook_payload"
      end
      # verify the required parameter 'ai_apply_job_posting_status_updated_webhook_payload' is set
      if @api_client.config.client_side_validation && ai_apply_job_posting_status_updated_webhook_payload.nil?
        fail ArgumentError, "Missing the required parameter 'ai_apply_job_posting_status_updated_webhook_payload' when calling DefaultApi.webhook_ai_apply_job_posting_status_updated_webhook_payload"
      end
      # resource path
      local_var_path = '/ai-apply-job-posting-status-updated'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Kombo-Signature'] = x_kombo_signature

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(ai_apply_job_posting_status_updated_webhook_payload)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.webhook_ai_apply_job_posting_status_updated_webhook_payload",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#webhook_ai_apply_job_posting_status_updated_webhook_payload\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Assessment: Order received
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param assessment_order_received_webhook_payload [AssessmentOrderReceivedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def webhook_assessment_order_received_webhook_payload(x_kombo_signature, assessment_order_received_webhook_payload, opts = {})
      webhook_assessment_order_received_webhook_payload_with_http_info(x_kombo_signature, assessment_order_received_webhook_payload, opts)
      nil
    end

    # Assessment: Order received
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param assessment_order_received_webhook_payload [AssessmentOrderReceivedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def webhook_assessment_order_received_webhook_payload_with_http_info(x_kombo_signature, assessment_order_received_webhook_payload, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.webhook_assessment_order_received_webhook_payload ...'
      end
      # verify the required parameter 'x_kombo_signature' is set
      if @api_client.config.client_side_validation && x_kombo_signature.nil?
        fail ArgumentError, "Missing the required parameter 'x_kombo_signature' when calling DefaultApi.webhook_assessment_order_received_webhook_payload"
      end
      # verify the required parameter 'assessment_order_received_webhook_payload' is set
      if @api_client.config.client_side_validation && assessment_order_received_webhook_payload.nil?
        fail ArgumentError, "Missing the required parameter 'assessment_order_received_webhook_payload' when calling DefaultApi.webhook_assessment_order_received_webhook_payload"
      end
      # resource path
      local_var_path = '/assessment:order-received'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Kombo-Signature'] = x_kombo_signature

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(assessment_order_received_webhook_payload)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.webhook_assessment_order_received_webhook_payload",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#webhook_assessment_order_received_webhook_payload\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Connection flow failed
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param connection_flow_failed_webhook_payload [ConnectionFlowFailedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def webhook_connection_flow_failed_webhook_payload(x_kombo_signature, connection_flow_failed_webhook_payload, opts = {})
      webhook_connection_flow_failed_webhook_payload_with_http_info(x_kombo_signature, connection_flow_failed_webhook_payload, opts)
      nil
    end

    # Connection flow failed
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param connection_flow_failed_webhook_payload [ConnectionFlowFailedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def webhook_connection_flow_failed_webhook_payload_with_http_info(x_kombo_signature, connection_flow_failed_webhook_payload, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.webhook_connection_flow_failed_webhook_payload ...'
      end
      # verify the required parameter 'x_kombo_signature' is set
      if @api_client.config.client_side_validation && x_kombo_signature.nil?
        fail ArgumentError, "Missing the required parameter 'x_kombo_signature' when calling DefaultApi.webhook_connection_flow_failed_webhook_payload"
      end
      # verify the required parameter 'connection_flow_failed_webhook_payload' is set
      if @api_client.config.client_side_validation && connection_flow_failed_webhook_payload.nil?
        fail ArgumentError, "Missing the required parameter 'connection_flow_failed_webhook_payload' when calling DefaultApi.webhook_connection_flow_failed_webhook_payload"
      end
      # resource path
      local_var_path = '/connection-flow-failed'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Kombo-Signature'] = x_kombo_signature

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(connection_flow_failed_webhook_payload)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.webhook_connection_flow_failed_webhook_payload",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#webhook_connection_flow_failed_webhook_payload\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Data changed
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param data_changed_webhook_payload [DataChangedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def webhook_data_changed_webhook_payload(x_kombo_signature, data_changed_webhook_payload, opts = {})
      webhook_data_changed_webhook_payload_with_http_info(x_kombo_signature, data_changed_webhook_payload, opts)
      nil
    end

    # Data changed
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param data_changed_webhook_payload [DataChangedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def webhook_data_changed_webhook_payload_with_http_info(x_kombo_signature, data_changed_webhook_payload, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.webhook_data_changed_webhook_payload ...'
      end
      # verify the required parameter 'x_kombo_signature' is set
      if @api_client.config.client_side_validation && x_kombo_signature.nil?
        fail ArgumentError, "Missing the required parameter 'x_kombo_signature' when calling DefaultApi.webhook_data_changed_webhook_payload"
      end
      # verify the required parameter 'data_changed_webhook_payload' is set
      if @api_client.config.client_side_validation && data_changed_webhook_payload.nil?
        fail ArgumentError, "Missing the required parameter 'data_changed_webhook_payload' when calling DefaultApi.webhook_data_changed_webhook_payload"
      end
      # resource path
      local_var_path = '/data-changed'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Kombo-Signature'] = x_kombo_signature

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(data_changed_webhook_payload)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.webhook_data_changed_webhook_payload",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#webhook_data_changed_webhook_payload\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Inline assessment: Order received
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param inline_assessment_order_received_webhook_payload [InlineAssessmentOrderReceivedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def webhook_inline_assessment_order_received_webhook_payload(x_kombo_signature, inline_assessment_order_received_webhook_payload, opts = {})
      webhook_inline_assessment_order_received_webhook_payload_with_http_info(x_kombo_signature, inline_assessment_order_received_webhook_payload, opts)
      nil
    end

    # Inline assessment: Order received
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param inline_assessment_order_received_webhook_payload [InlineAssessmentOrderReceivedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def webhook_inline_assessment_order_received_webhook_payload_with_http_info(x_kombo_signature, inline_assessment_order_received_webhook_payload, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.webhook_inline_assessment_order_received_webhook_payload ...'
      end
      # verify the required parameter 'x_kombo_signature' is set
      if @api_client.config.client_side_validation && x_kombo_signature.nil?
        fail ArgumentError, "Missing the required parameter 'x_kombo_signature' when calling DefaultApi.webhook_inline_assessment_order_received_webhook_payload"
      end
      # verify the required parameter 'inline_assessment_order_received_webhook_payload' is set
      if @api_client.config.client_side_validation && inline_assessment_order_received_webhook_payload.nil?
        fail ArgumentError, "Missing the required parameter 'inline_assessment_order_received_webhook_payload' when calling DefaultApi.webhook_inline_assessment_order_received_webhook_payload"
      end
      # resource path
      local_var_path = '/inline-assessment:order-received'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Kombo-Signature'] = x_kombo_signature

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(inline_assessment_order_received_webhook_payload)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.webhook_inline_assessment_order_received_webhook_payload",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#webhook_inline_assessment_order_received_webhook_payload\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Integration created
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param integration_created_webhook_payload [IntegrationCreatedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def webhook_integration_created_webhook_payload(x_kombo_signature, integration_created_webhook_payload, opts = {})
      webhook_integration_created_webhook_payload_with_http_info(x_kombo_signature, integration_created_webhook_payload, opts)
      nil
    end

    # Integration created
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param integration_created_webhook_payload [IntegrationCreatedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def webhook_integration_created_webhook_payload_with_http_info(x_kombo_signature, integration_created_webhook_payload, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.webhook_integration_created_webhook_payload ...'
      end
      # verify the required parameter 'x_kombo_signature' is set
      if @api_client.config.client_side_validation && x_kombo_signature.nil?
        fail ArgumentError, "Missing the required parameter 'x_kombo_signature' when calling DefaultApi.webhook_integration_created_webhook_payload"
      end
      # verify the required parameter 'integration_created_webhook_payload' is set
      if @api_client.config.client_side_validation && integration_created_webhook_payload.nil?
        fail ArgumentError, "Missing the required parameter 'integration_created_webhook_payload' when calling DefaultApi.webhook_integration_created_webhook_payload"
      end
      # resource path
      local_var_path = '/integration-created'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Kombo-Signature'] = x_kombo_signature

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(integration_created_webhook_payload)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.webhook_integration_created_webhook_payload",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#webhook_integration_created_webhook_payload\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Integration deleted
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param integration_deleted_webhook_payload [IntegrationDeletedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def webhook_integration_deleted_webhook_payload(x_kombo_signature, integration_deleted_webhook_payload, opts = {})
      webhook_integration_deleted_webhook_payload_with_http_info(x_kombo_signature, integration_deleted_webhook_payload, opts)
      nil
    end

    # Integration deleted
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param integration_deleted_webhook_payload [IntegrationDeletedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def webhook_integration_deleted_webhook_payload_with_http_info(x_kombo_signature, integration_deleted_webhook_payload, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.webhook_integration_deleted_webhook_payload ...'
      end
      # verify the required parameter 'x_kombo_signature' is set
      if @api_client.config.client_side_validation && x_kombo_signature.nil?
        fail ArgumentError, "Missing the required parameter 'x_kombo_signature' when calling DefaultApi.webhook_integration_deleted_webhook_payload"
      end
      # verify the required parameter 'integration_deleted_webhook_payload' is set
      if @api_client.config.client_side_validation && integration_deleted_webhook_payload.nil?
        fail ArgumentError, "Missing the required parameter 'integration_deleted_webhook_payload' when calling DefaultApi.webhook_integration_deleted_webhook_payload"
      end
      # resource path
      local_var_path = '/integration-deleted'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Kombo-Signature'] = x_kombo_signature

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(integration_deleted_webhook_payload)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.webhook_integration_deleted_webhook_payload",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#webhook_integration_deleted_webhook_payload\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Integration state changed
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param integration_state_changed_webhook_payload [IntegrationStateChangedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def webhook_integration_state_changed_webhook_payload(x_kombo_signature, integration_state_changed_webhook_payload, opts = {})
      webhook_integration_state_changed_webhook_payload_with_http_info(x_kombo_signature, integration_state_changed_webhook_payload, opts)
      nil
    end

    # Integration state changed
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param integration_state_changed_webhook_payload [IntegrationStateChangedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def webhook_integration_state_changed_webhook_payload_with_http_info(x_kombo_signature, integration_state_changed_webhook_payload, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.webhook_integration_state_changed_webhook_payload ...'
      end
      # verify the required parameter 'x_kombo_signature' is set
      if @api_client.config.client_side_validation && x_kombo_signature.nil?
        fail ArgumentError, "Missing the required parameter 'x_kombo_signature' when calling DefaultApi.webhook_integration_state_changed_webhook_payload"
      end
      # verify the required parameter 'integration_state_changed_webhook_payload' is set
      if @api_client.config.client_side_validation && integration_state_changed_webhook_payload.nil?
        fail ArgumentError, "Missing the required parameter 'integration_state_changed_webhook_payload' when calling DefaultApi.webhook_integration_state_changed_webhook_payload"
      end
      # resource path
      local_var_path = '/integration-state-changed'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Kombo-Signature'] = x_kombo_signature

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(integration_state_changed_webhook_payload)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.webhook_integration_state_changed_webhook_payload",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#webhook_integration_state_changed_webhook_payload\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Remote event received
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param remote_event_received_webhook_payload [RemoteEventReceivedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def webhook_remote_event_received_webhook_payload(x_kombo_signature, remote_event_received_webhook_payload, opts = {})
      webhook_remote_event_received_webhook_payload_with_http_info(x_kombo_signature, remote_event_received_webhook_payload, opts)
      nil
    end

    # Remote event received
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param remote_event_received_webhook_payload [RemoteEventReceivedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def webhook_remote_event_received_webhook_payload_with_http_info(x_kombo_signature, remote_event_received_webhook_payload, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.webhook_remote_event_received_webhook_payload ...'
      end
      # verify the required parameter 'x_kombo_signature' is set
      if @api_client.config.client_side_validation && x_kombo_signature.nil?
        fail ArgumentError, "Missing the required parameter 'x_kombo_signature' when calling DefaultApi.webhook_remote_event_received_webhook_payload"
      end
      # verify the required parameter 'remote_event_received_webhook_payload' is set
      if @api_client.config.client_side_validation && remote_event_received_webhook_payload.nil?
        fail ArgumentError, "Missing the required parameter 'remote_event_received_webhook_payload' when calling DefaultApi.webhook_remote_event_received_webhook_payload"
      end
      # resource path
      local_var_path = '/remote-event-received'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Kombo-Signature'] = x_kombo_signature

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(remote_event_received_webhook_payload)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.webhook_remote_event_received_webhook_payload",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#webhook_remote_event_received_webhook_payload\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Sync finished
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param sync_finished_webhook_payload [SyncFinishedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def webhook_sync_finished_webhook_payload(x_kombo_signature, sync_finished_webhook_payload, opts = {})
      webhook_sync_finished_webhook_payload_with_http_info(x_kombo_signature, sync_finished_webhook_payload, opts)
      nil
    end

    # Sync finished
    # @param x_kombo_signature [String] HMAC signature for webhook verification. See the webhook documentation for details on how to verify this signature.
    # @param sync_finished_webhook_payload [SyncFinishedWebhookPayload] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def webhook_sync_finished_webhook_payload_with_http_info(x_kombo_signature, sync_finished_webhook_payload, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DefaultApi.webhook_sync_finished_webhook_payload ...'
      end
      # verify the required parameter 'x_kombo_signature' is set
      if @api_client.config.client_side_validation && x_kombo_signature.nil?
        fail ArgumentError, "Missing the required parameter 'x_kombo_signature' when calling DefaultApi.webhook_sync_finished_webhook_payload"
      end
      # verify the required parameter 'sync_finished_webhook_payload' is set
      if @api_client.config.client_side_validation && sync_finished_webhook_payload.nil?
        fail ArgumentError, "Missing the required parameter 'sync_finished_webhook_payload' when calling DefaultApi.webhook_sync_finished_webhook_payload"
      end
      # resource path
      local_var_path = '/sync-finished'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Kombo-Signature'] = x_kombo_signature

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(sync_finished_webhook_payload)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKey']

      new_options = opts.merge(
        :operation => :"DefaultApi.webhook_sync_finished_webhook_payload",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#webhook_sync_finished_webhook_payload\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
