=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Kombo::AIApplyApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AIApplyApi' do
  before do
    # run before each test
    @api_instance = Kombo::AIApplyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AIApplyApi' do
    it 'should create an instance of AIApplyApi' do
      expect(@api_instance).to be_instance_of(Kombo::AIApplyApi)
    end
  end

  # unit tests for get_ai_apply_applications
  # Get applications
  # Get all applications.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor An optional cursor string used for pagination. This can be retrieved from the &#x60;next&#x60; property of the previous page response.
  # @option opts [Integer] :page_size The number of results to return per page. Maximum is 250.
  # @option opts [String] :ids Filter by a comma-separated list of IDs such as &#x60;222k7eCGyUdgt2JWZDNnkDs3,B5DVmypWENfU6eMe6gYDyJG3&#x60;.
  # @option opts [String] :job_posting_ids Filter by a comma-separated list of job posting IDs such as &#x60;89V6GEKpdZwqbxQz59n1ftFb,kcGHREEXCMF26Yhpuyh1gDVE&#x60;.
  # @return [GetAiApplyApplicationsPositiveResponse]
  describe 'get_ai_apply_applications test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_ai_apply_career_sites
  # Get career sites
  # Get all career sites.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor An optional cursor string used for pagination. This can be retrieved from the &#x60;next&#x60; property of the previous page response.
  # @option opts [Integer] :page_size The number of results to return per page. Maximum is 250.
  # @option opts [String] :ids Filter by a comma-separated list of IDs such as &#x60;222k7eCGyUdgt2JWZDNnkDs3,B5DVmypWENfU6eMe6gYDyJG3&#x60;.
  # @return [GetAiApplyCareerSitesPositiveResponse]
  describe 'get_ai_apply_career_sites test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_ai_apply_postings
  # Get job postings
  # Get all job postings. To get the application form and submit applications, use the POST /postings/:id/inquire endpoint.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor An optional cursor string used for pagination. This can be retrieved from the &#x60;next&#x60; property of the previous page response.
  # @option opts [Integer] :page_size The number of results to return per page. Maximum is 250.
  # @option opts [String] :ids Filter by a comma-separated list of IDs such as &#x60;222k7eCGyUdgt2JWZDNnkDs3,B5DVmypWENfU6eMe6gYDyJG3&#x60;.
  # @option opts [String] :career_site_ids Filter by a comma-separated list of career site IDs such as &#x60;A8m9k9RhjNokMfRTWtpQ99VtH,rCbkAA3pvcKjsFYwEeXtCQkc&#x60;.
  # @option opts [String] :job_codes Filter by a comma-separated list of job codes such as &#x60;ACME_13,ACME_14&#x60;.
  # @return [GetAiApplyPostingsPositiveResponse]
  describe 'get_ai_apply_postings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_ai_apply_unified_api_jobs
  # Get jobs
  # Get jobs in a backwards compatible way as you would [via Kombo&#39;s unified API](https://docs.kombo.dev/ats/v1/get-jobs). This is not the recommended way to get jobs with AI Apply.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor An optional cursor string used for pagination. This can be retrieved from the &#x60;next&#x60; property of the previous page response.
  # @option opts [Integer] :page_size The number of results to return per page. Maximum is 5.
  # @option opts [String] :ids Filter by a comma-separated list of IDs such as &#x60;222k7eCGyUdgt2JWZDNnkDs3,B5DVmypWENfU6eMe6gYDyJG3&#x60;.
  # @option opts [String] :remote_ids This parameter exists for backwards compatibility with Kombo&#39;s unified API. Supplying a comma-separated list of remote IDs such as &#x60;32,33&#x60; will return no jobs because AI Apply does not interface with a remote system that issues remote IDs.
  # @option opts [String] :job_codes Filter by a comma-separated list of job codes such as &#x60;ACME_12,ACME_14&#x60;.
  # @option opts [String] :career_site_ids Filter by a comma-separated list of career site IDs such as &#x60;A8m9k9RhjNokMfRTWtpQ99VtH,rCbkAA3pvcKjsFYwEeXtCQkc&#x60;.
  # @return [GetAiApplyUnifiedApiJobsPositiveResponse]
  describe 'get_ai_apply_unified_api_jobs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_ai_apply_apply
  # Submit job application
  # Submit a job application using a submission token. The application will be queued and processed asynchronously. Returns ID to track progress and match with webhooks.
  # @param [Hash] opts the optional parameters
  # @option opts [PostAiApplyApplyRequestBody] :post_ai_apply_apply_request_body POST /ai-apply/apply Request body
  # @return [PostAiApplyApplyPositiveResponse]
  describe 'post_ai_apply_apply test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_ai_apply_career_sites
  # Create a career site
  # Create a career site entry. Career sites are required to be specified when parsing job postings, grouping them under a single entity.
  # @param [Hash] opts the optional parameters
  # @option opts [PostAiApplyCareerSitesRequestBody] :post_ai_apply_career_sites_request_body POST /ai-apply/career-sites Request body
  # @return [PostAiApplyCareerSitesPositiveResponse]
  describe 'post_ai_apply_career_sites test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_ai_apply_postings
  # Parse a job posting
  # Submit a job posting URL to be parsed asynchronously. Returns ID to track progress.
  # @param [Hash] opts the optional parameters
  # @option opts [PostAiApplyPostingsRequestBody] :post_ai_apply_postings_request_body POST /ai-apply/postings Request body
  # @return [PostAiApplyPostingsPositiveResponse]
  describe 'post_ai_apply_postings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_ai_apply_postings_posting_id_inquire
  # Inquire about a job posting and the application f…
  # Receive the application form (screening questions) for a job posting and a submission token. This endpoint must be called before submitting an application to ensure you have the latest questions and a valid submission token. The submission token is valid for 12 hours and prevents duplicate submissions. The application form may contain conditional questions that are only shown based on answers to previous questions (check the display_when field).
  # @param posting_id The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :body POST /ai-apply/postings/:posting_id/inquire Request body
  # @return [PostAiApplyPostingsPostingIdInquirePositiveResponse]
  describe 'post_ai_apply_postings_posting_id_inquire test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_ai_apply_postings_posting_id_parse
  # Re-parse an existing job posting
  # Trigger re-parsing of an already parsed job posting.
  # @param posting_id The ID of the job posting to parse a new revision for
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :body POST /ai-apply/postings/:posting_id/parse Request body
  # @return [PostAiApplyPostingsPostingIdParsePositiveResponse]
  describe 'post_ai_apply_postings_posting_id_parse test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_ai_apply_unified_api_jobs_job_id_applications
  # Create application
  # Create applications in a backwards compatible way as you would [via Kombo&#39;s unified API](https://docs.kombo.dev/ats/v1/post-jobs-job-id-applications). This is not the recommended way to create applications with AI Apply.
  # @param job_id The Kombo ID or Remote ID of the Job this candidate should apply for. If you want to use the ID of the integrated system (remote_id) you need to prefix the id with \&quot;remote:\&quot;. You can use the remote ID if you do not want to sync jobs.
  # @param [Hash] opts the optional parameters
  # @option opts [PostAiApplyUnifiedApiJobsJobIdApplicationsRequestBody] :post_ai_apply_unified_api_jobs_job_id_applications_request_body POST /ai-apply/unified-api/jobs/:job_id/applications Request body
  # @return [PostAiApplyUnifiedApiJobsJobIdApplicationsPositiveResponse]
  describe 'post_ai_apply_unified_api_jobs_job_id_applications test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
