=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kombo::DataChangedWebhookPayloadData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kombo::DataChangedWebhookPayloadData do
  let(:instance) { Kombo::DataChangedWebhookPayloadData.new }

  describe 'test an instance of DataChangedWebhookPayloadData' do
    it 'should create an instance of DataChangedWebhookPayloadData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kombo::DataChangedWebhookPayloadData)
    end
  end

  describe 'test attribute "integration_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "integration_tool"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "integration_category"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["HRIS", "ATS", "ASSESSMENT"])
      # validator.allowable_values.each do |value|
      #   expect { instance.integration_category = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "changed_models"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
