=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kombo::GetCustomDatevEauRequestsEauIdPositiveResponseDataRawFeedbacksFromHealthInsuranceInnerIncapacityForWork
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kombo::GetCustomDatevEauRequestsEauIdPositiveResponseDataRawFeedbacksFromHealthInsuranceInnerIncapacityForWork do
  let(:instance) { Kombo::GetCustomDatevEauRequestsEauIdPositiveResponseDataRawFeedbacksFromHealthInsuranceInnerIncapacityForWork.new }

  describe 'test an instance of GetCustomDatevEauRequestsEauIdPositiveResponseDataRawFeedbacksFromHealthInsuranceInnerIncapacityForWork' do
    it 'should create an instance of GetCustomDatevEauRequestsEauIdPositiveResponseDataRawFeedbacksFromHealthInsuranceInnerIncapacityForWork' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kombo::GetCustomDatevEauRequestsEauIdPositiveResponseDataRawFeedbacksFromHealthInsuranceInnerIncapacityForWork)
    end
  end

  describe 'test attribute "start_work_incapacity_employer"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "start_work_incapacity_au"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "end_work_incapacity_au"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "actual_end_work_incapacity_au"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "date_of_diagnosis"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "flag_current_work_incapacity"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "accident_at_work"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "assignment_accident_insurance_doctor"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "other_accident"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "start_hospitalisation"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "end_hospitalisation"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "initial_certificate"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "automatic_feedback_until"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
