=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kombo::GetLmsUsersParameterIncludeDeleted
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kombo::GetLmsUsersParameterIncludeDeleted do
  #let(:instance) { Kombo::GetLmsUsersParameterIncludeDeleted.new }

  describe 'test an instance of GetLmsUsersParameterIncludeDeleted' do
    it 'should create an instance of GetLmsUsersParameterIncludeDeleted' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kombo::GetLmsUsersParameterIncludeDeleted)
    end
  end

end
