=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kombo::GetToolsCategoryPositiveResponseDataToolsInnerCoverageReadModelsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kombo::GetToolsCategoryPositiveResponseDataToolsInnerCoverageReadModelsInner do
  let(:instance) { Kombo::GetToolsCategoryPositiveResponseDataToolsInnerCoverageReadModelsInner.new }

  describe 'test an instance of GetToolsCategoryPositiveResponseDataToolsInnerCoverageReadModelsInner' do
    it 'should create an instance of GetToolsCategoryPositiveResponseDataToolsInnerCoverageReadModelsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kombo::GetToolsCategoryPositiveResponseDataToolsInnerCoverageReadModelsInner)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "label"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "coverage_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["SUPPORTED", "UNSUPPORTED", "NOT_IMPLEMENTED", "UNKNOWN"])
      # validator.allowable_values.each do |value|
      #   expect { instance.coverage_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "fields"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
