=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kombo::GetHrisTimesheetsParameterIncludeDeleted
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kombo::GetHrisTimesheetsParameterIncludeDeleted do
  let(:instance) { Kombo::GetHrisTimesheetsParameterIncludeDeleted.new }

  describe 'test an instance of GetHrisTimesheetsParameterIncludeDeleted' do
    it 'should create an instance of GetHrisTimesheetsParameterIncludeDeleted' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kombo::GetHrisTimesheetsParameterIncludeDeleted)
    end
  end

end
