=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kombo::IntegrationStateChangedWebhookPayloadData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kombo::IntegrationStateChangedWebhookPayloadData do
  let(:instance) { Kombo::IntegrationStateChangedWebhookPayloadData.new }

  describe 'test an instance of IntegrationStateChangedWebhookPayloadData' do
    it 'should create an instance of IntegrationStateChangedWebhookPayloadData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kombo::IntegrationStateChangedWebhookPayloadData)
    end
  end

  describe 'test attribute "integration_tool"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "integration_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "integration_category"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["HRIS", "ATS", "ASSESSMENT"])
      # validator.allowable_values.each do |value|
      #   expect { instance.integration_category = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "end_user"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "qa_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["PENDING", "FAILED", "PASSED"])
      # validator.allowable_values.each do |value|
      #   expect { instance.qa_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "state"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ACTIVE", "INVALID", "INACTIVE"])
      # validator.allowable_values.each do |value|
      #   expect { instance.state = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "updated_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
