=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kombo::PostAtsCandidatesRequestBodyRemoteFieldsAllOfJobylon
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kombo::PostAtsCandidatesRequestBodyRemoteFieldsAllOfJobylon do
  let(:instance) { Kombo::PostAtsCandidatesRequestBodyRemoteFieldsAllOfJobylon.new }

  describe 'test an instance of PostAtsCandidatesRequestBodyRemoteFieldsAllOfJobylon' do
    it 'should create an instance of PostAtsCandidatesRequestBodyRemoteFieldsAllOfJobylon' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kombo::PostAtsCandidatesRequestBodyRemoteFieldsAllOfJobylon)
    end
  end

  describe 'test attribute "application"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
