=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kombo::PostCustomDatevPassthroughRequestBody
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kombo::PostCustomDatevPassthroughRequestBody do
  let(:instance) { Kombo::PostCustomDatevPassthroughRequestBody.new }

  describe 'test an instance of PostCustomDatevPassthroughRequestBody' do
    it 'should create an instance of PostCustomDatevPassthroughRequestBody' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kombo::PostCustomDatevPassthroughRequestBody)
    end
  end

  describe 'test attribute "file_content"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "accounting_month"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "target_system"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["LODAS", "LuG"])
      # validator.allowable_values.each do |value|
      #   expect { instance.target_system = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "file_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["STAMMDATEN", "BEWEGUNGSDATEN"])
      # validator.allowable_values.each do |value|
      #   expect { instance.file_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "file_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
