=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kombo::PostAtsImportTrackedApplicationPositiveResponseDataImportedIdSuccessfactors
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kombo::PostAtsImportTrackedApplicationPositiveResponseDataImportedIdSuccessfactors do
  let(:instance) { Kombo::PostAtsImportTrackedApplicationPositiveResponseDataImportedIdSuccessfactors.new }

  describe 'test an instance of PostAtsImportTrackedApplicationPositiveResponseDataImportedIdSuccessfactors' do
    it 'should create an instance of PostAtsImportTrackedApplicationPositiveResponseDataImportedIdSuccessfactors' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kombo::PostAtsImportTrackedApplicationPositiveResponseDataImportedIdSuccessfactors)
    end
  end

  describe 'test attribute "id_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["application_remote_id"])
      # validator.allowable_values.each do |value|
      #   expect { instance.id_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "application_remote_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
