=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kombo::PostHrisEmployeesRequestBodyRemoteFieldsAdpworkforcenow
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kombo::PostHrisEmployeesRequestBodyRemoteFieldsAdpworkforcenow do
  let(:instance) { Kombo::PostHrisEmployeesRequestBodyRemoteFieldsAdpworkforcenow.new }

  describe 'test an instance of PostHrisEmployeesRequestBodyRemoteFieldsAdpworkforcenow' do
    it 'should create an instance of PostHrisEmployeesRequestBodyRemoteFieldsAdpworkforcenow' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kombo::PostHrisEmployeesRequestBodyRemoteFieldsAdpworkforcenow)
    end
  end

  describe 'test attribute "onboarding_template_code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "applicant_payroll_profile_group_code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "manager_position_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "home_organization_unit_code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "personal_email"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
