=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kombo::PostHrisProvisioningGroupsGroupIdDiffRequestBodyOptions
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kombo::PostHrisProvisioningGroupsGroupIdDiffRequestBodyOptions do
  let(:instance) { Kombo::PostHrisProvisioningGroupsGroupIdDiffRequestBodyOptions.new }

  describe 'test an instance of PostHrisProvisioningGroupsGroupIdDiffRequestBodyOptions' do
    it 'should create an instance of PostHrisProvisioningGroupsGroupIdDiffRequestBodyOptions' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kombo::PostHrisProvisioningGroupsGroupIdDiffRequestBodyOptions)
    end
  end

  describe 'test attribute "employee_fields"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["id", "remote_id", "first_name", "last_name", "groups", "avatar", "work_location_id", "legal_entity_id"])
      # validator.allowable_values.each do |value|
      #   expect { instance.employee_fields = value }.not_to raise_error
      # end
    end
  end

end
