=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kombo::Schema2AnyOf3OptionsAnyOfEntriesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kombo::Schema2AnyOf3OptionsAnyOfEntriesInner do
  let(:instance) { Kombo::Schema2AnyOf3OptionsAnyOfEntriesInner.new }

  describe 'test an instance of Schema2AnyOf3OptionsAnyOfEntriesInner' do
    it 'should create an instance of Schema2AnyOf3OptionsAnyOfEntriesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Kombo::Schema2AnyOf3OptionsAnyOfEntriesInner)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "label"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "unified_value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "remote_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
