=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  class AssessmentOrderReceivedWebhookPayloadData < ApiModelBase
    # The unique identifier of the assessment order.
    attr_accessor :id

    # The identifier of the assessment package.
    attr_accessor :package_id

    # The current status of the assessment order.
    attr_accessor :status

    # The unique identifier of the integration.
    attr_accessor :integration_id

    attr_accessor :candidate

    attr_accessor :application

    attr_accessor :job

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'package_id' => :'package_id',
        :'status' => :'status',
        :'integration_id' => :'integration_id',
        :'candidate' => :'candidate',
        :'application' => :'application',
        :'job' => :'job'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'package_id' => :'String',
        :'status' => :'String',
        :'integration_id' => :'String',
        :'candidate' => :'AssessmentOrderReceivedWebhookPayloadDataCandidate',
        :'application' => :'AssessmentOrderReceivedWebhookPayloadDataApplication',
        :'job' => :'AssessmentOrderReceivedWebhookPayloadDataJob'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::AssessmentOrderReceivedWebhookPayloadData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::AssessmentOrderReceivedWebhookPayloadData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'package_id')
        self.package_id = attributes[:'package_id']
      else
        self.package_id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'integration_id')
        self.integration_id = attributes[:'integration_id']
      else
        self.integration_id = nil
      end

      if attributes.key?(:'candidate')
        self.candidate = attributes[:'candidate']
      else
        self.candidate = nil
      end

      if attributes.key?(:'application')
        self.application = attributes[:'application']
      else
        self.application = nil
      end

      if attributes.key?(:'job')
        self.job = attributes[:'job']
      else
        self.job = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @package_id.nil?
        invalid_properties.push('invalid value for "package_id", package_id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @integration_id.nil?
        invalid_properties.push('invalid value for "integration_id", integration_id cannot be nil.')
      end

      if @candidate.nil?
        invalid_properties.push('invalid value for "candidate", candidate cannot be nil.')
      end

      if @application.nil?
        invalid_properties.push('invalid value for "application", application cannot be nil.')
      end

      if @job.nil?
        invalid_properties.push('invalid value for "job", job cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @package_id.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["OPEN", "COMPLETED", "CANCELLED", "REJECTED"])
      return false unless status_validator.valid?(@status)
      return false if @integration_id.nil?
      return false if @candidate.nil?
      return false if @application.nil?
      return false if @job.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] package_id Value to be assigned
    def package_id=(package_id)
      if package_id.nil?
        fail ArgumentError, 'package_id cannot be nil'
      end

      @package_id = package_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["OPEN", "COMPLETED", "CANCELLED", "REJECTED"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] integration_id Value to be assigned
    def integration_id=(integration_id)
      if integration_id.nil?
        fail ArgumentError, 'integration_id cannot be nil'
      end

      @integration_id = integration_id
    end

    # Custom attribute writer method with validation
    # @param [Object] candidate Value to be assigned
    def candidate=(candidate)
      if candidate.nil?
        fail ArgumentError, 'candidate cannot be nil'
      end

      @candidate = candidate
    end

    # Custom attribute writer method with validation
    # @param [Object] application Value to be assigned
    def application=(application)
      if application.nil?
        fail ArgumentError, 'application cannot be nil'
      end

      @application = application
    end

    # Custom attribute writer method with validation
    # @param [Object] job Value to be assigned
    def job=(job)
      if job.nil?
        fail ArgumentError, 'job cannot be nil'
      end

      @job = job
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          package_id == o.package_id &&
          status == o.status &&
          integration_id == o.integration_id &&
          candidate == o.candidate &&
          application == o.application &&
          job == o.job
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, package_id, status, integration_id, candidate, application, job].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
