=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  class GetAtsJobsParameterStatus
    OPEN = "OPEN".freeze
    CLOSED = "CLOSED".freeze
    DRAFT = "DRAFT".freeze
    ARCHIVED = "ARCHIVED".freeze

    def self.all_vars
      @all_vars ||= [OPEN, CLOSED, DRAFT, ARCHIVED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if GetAtsJobsParameterStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #GetAtsJobsParameterStatus"
    end
  end
end
