=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  # Specific attachment type restrictions for each attachment type. If null, we don' have information about the attachment type restrictions.
  class GetAtsActionsAtsCreateCandidatePositiveResponseDataAttachmentRestrictionsTypes < ApiModelBase
    attr_accessor :cv

    attr_accessor :cover_letter

    attr_accessor :other

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'cv' => :'CV',
        :'cover_letter' => :'COVER_LETTER',
        :'other' => :'OTHER'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'cv' => :'GetAtsActionsAtsCreateCandidatePositiveResponseDataAttachmentRestrictionsTypesCV',
        :'cover_letter' => :'GetAtsActionsAtsCreateCandidatePositiveResponseDataAttachmentRestrictionsTypesCOVERLETTER',
        :'other' => :'GetAtsActionsAtsCreateCandidatePositiveResponseDataAttachmentRestrictionsTypesOTHER'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::GetAtsActionsAtsCreateCandidatePositiveResponseDataAttachmentRestrictionsTypes` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::GetAtsActionsAtsCreateCandidatePositiveResponseDataAttachmentRestrictionsTypes`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'cv')
        self.cv = attributes[:'cv']
      else
        self.cv = nil
      end

      if attributes.key?(:'cover_letter')
        self.cover_letter = attributes[:'cover_letter']
      else
        self.cover_letter = nil
      end

      if attributes.key?(:'other')
        self.other = attributes[:'other']
      else
        self.other = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @cv.nil?
        invalid_properties.push('invalid value for "cv", cv cannot be nil.')
      end

      if @cover_letter.nil?
        invalid_properties.push('invalid value for "cover_letter", cover_letter cannot be nil.')
      end

      if @other.nil?
        invalid_properties.push('invalid value for "other", other cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @cv.nil?
      return false if @cover_letter.nil?
      return false if @other.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] cv Value to be assigned
    def cv=(cv)
      if cv.nil?
        fail ArgumentError, 'cv cannot be nil'
      end

      @cv = cv
    end

    # Custom attribute writer method with validation
    # @param [Object] cover_letter Value to be assigned
    def cover_letter=(cover_letter)
      if cover_letter.nil?
        fail ArgumentError, 'cover_letter cannot be nil'
      end

      @cover_letter = cover_letter
    end

    # Custom attribute writer method with validation
    # @param [Object] other Value to be assigned
    def other=(other)
      if other.nil?
        fail ArgumentError, 'other cannot be nil'
      end

      @other = other
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          cv == o.cv &&
          cover_letter == o.cover_letter &&
          other == o.other
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [cv, cover_letter, other].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
