=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  class GetToolsCategoryPositiveResponseDataToolsInner < ApiModelBase
    attr_accessor :id

    attr_accessor :label

    # Internal label that can help you debug specific variants of the integration. Only show the `label` to your users.
    attr_accessor :internal_label

    attr_accessor :assets

    # Markdown formatted text that describes details about the paid API. `null` if the tool is not paid.
    attr_accessor :paid_api_details_markdown

    # Markdown formatted text that describes details about the fast track process. `null` if the fast track process is not available.
    attr_accessor :fast_track_details_markdown

    # Markdown formatted text that describes partnership requirements. `null` if the tool does not require a partnership.
    attr_accessor :partner_only_details_markdown

    # URL to the connection guide for this tool. `null` if no connection guide is available.
    attr_accessor :connection_guide_url

    attr_accessor :coverage

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'label' => :'label',
        :'internal_label' => :'internal_label',
        :'assets' => :'assets',
        :'paid_api_details_markdown' => :'paid_api_details_markdown',
        :'fast_track_details_markdown' => :'fast_track_details_markdown',
        :'partner_only_details_markdown' => :'partner_only_details_markdown',
        :'connection_guide_url' => :'connection_guide_url',
        :'coverage' => :'coverage'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'label' => :'String',
        :'internal_label' => :'String',
        :'assets' => :'GetToolsCategoryPositiveResponseDataToolsInnerAssets',
        :'paid_api_details_markdown' => :'String',
        :'fast_track_details_markdown' => :'String',
        :'partner_only_details_markdown' => :'String',
        :'connection_guide_url' => :'String',
        :'coverage' => :'GetToolsCategoryPositiveResponseDataToolsInnerCoverage'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'internal_label',
        :'paid_api_details_markdown',
        :'fast_track_details_markdown',
        :'partner_only_details_markdown',
        :'connection_guide_url',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::GetToolsCategoryPositiveResponseDataToolsInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::GetToolsCategoryPositiveResponseDataToolsInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'label')
        self.label = attributes[:'label']
      else
        self.label = nil
      end

      if attributes.key?(:'internal_label')
        self.internal_label = attributes[:'internal_label']
      else
        self.internal_label = nil
      end

      if attributes.key?(:'assets')
        self.assets = attributes[:'assets']
      else
        self.assets = nil
      end

      if attributes.key?(:'paid_api_details_markdown')
        self.paid_api_details_markdown = attributes[:'paid_api_details_markdown']
      else
        self.paid_api_details_markdown = nil
      end

      if attributes.key?(:'fast_track_details_markdown')
        self.fast_track_details_markdown = attributes[:'fast_track_details_markdown']
      else
        self.fast_track_details_markdown = nil
      end

      if attributes.key?(:'partner_only_details_markdown')
        self.partner_only_details_markdown = attributes[:'partner_only_details_markdown']
      else
        self.partner_only_details_markdown = nil
      end

      if attributes.key?(:'connection_guide_url')
        self.connection_guide_url = attributes[:'connection_guide_url']
      else
        self.connection_guide_url = nil
      end

      if attributes.key?(:'coverage')
        self.coverage = attributes[:'coverage']
      else
        self.coverage = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @label.nil?
        invalid_properties.push('invalid value for "label", label cannot be nil.')
      end

      if @assets.nil?
        invalid_properties.push('invalid value for "assets", assets cannot be nil.')
      end

      if @coverage.nil?
        invalid_properties.push('invalid value for "coverage", coverage cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @label.nil?
      return false if @assets.nil?
      return false if @coverage.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] label Value to be assigned
    def label=(label)
      if label.nil?
        fail ArgumentError, 'label cannot be nil'
      end

      @label = label
    end

    # Custom attribute writer method with validation
    # @param [Object] assets Value to be assigned
    def assets=(assets)
      if assets.nil?
        fail ArgumentError, 'assets cannot be nil'
      end

      @assets = assets
    end

    # Custom attribute writer method with validation
    # @param [Object] coverage Value to be assigned
    def coverage=(coverage)
      if coverage.nil?
        fail ArgumentError, 'coverage cannot be nil'
      end

      @coverage = coverage
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          label == o.label &&
          internal_label == o.internal_label &&
          assets == o.assets &&
          paid_api_details_markdown == o.paid_api_details_markdown &&
          fast_track_details_markdown == o.fast_track_details_markdown &&
          partner_only_details_markdown == o.partner_only_details_markdown &&
          connection_guide_url == o.connection_guide_url &&
          coverage == o.coverage
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, label, internal_label, assets, paid_api_details_markdown, fast_track_details_markdown, partner_only_details_markdown, connection_guide_url, coverage].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
