=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  class PatchHrisEmployeesEmployeeIdRequestBody < ApiModelBase
    # The first name of the employee.
    attr_accessor :first_name

    # The last name of the employee.
    attr_accessor :last_name

    # The email address of the employee to be updated. For tools where the personal email address is required, we map this input to the personal email. This is documented on a per-tool basis.
    attr_accessor :work_email

    # The gender of the employee.
    attr_accessor :gender

    # The title of the position this person is working in.
    attr_accessor :job_title

    attr_accessor :home_address

    # The employee's date of birth. This is a plain date (i.e., `yyyy-MM-dd`), all time information is discarded.
    attr_accessor :date_of_birth

    attr_accessor :mobile_phone_number

    attr_accessor :home_phone_number

    # The uppercase two-letter ISO country (e.g., `DE`). For systems that use codes in formats other than `ISO 3166-1 alpha-2`, Kombo transforms the ISO Codes to the appropriate value.
    attr_accessor :nationality

    # Start date of the employee. Also considered to be the hire date. This is a plain date (i.e., `yyyy-MM-dd`), all time information is discarded.
    attr_accessor :start_date

    # The Kombo ID of the legal entity the employee should be in. This field is required for certain integrations.
    attr_accessor :legal_entity_id

    # The Kombo ID of the location the employee should be in. This field is required for certain integrations.
    attr_accessor :location_id

    attr_accessor :remote_fields

    # The social security number of the employee.
    attr_accessor :ssn

    # The marital status of an employee.
    attr_accessor :marital_status

    # The date on which the employment ends. This date can be in the past or in the future. This is a plain date (i.e., `yyyy-MM-dd`), all time information is discarded.
    attr_accessor :termination_date

    # Tax ID of the employee. Most countries have different formats of that. In Germany, this is the `Steuer ID` and in the US it's the `TIN`.
    attr_accessor :tax_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'first_name' => :'first_name',
        :'last_name' => :'last_name',
        :'work_email' => :'work_email',
        :'gender' => :'gender',
        :'job_title' => :'job_title',
        :'home_address' => :'home_address',
        :'date_of_birth' => :'date_of_birth',
        :'mobile_phone_number' => :'mobile_phone_number',
        :'home_phone_number' => :'home_phone_number',
        :'nationality' => :'nationality',
        :'start_date' => :'start_date',
        :'legal_entity_id' => :'legal_entity_id',
        :'location_id' => :'location_id',
        :'remote_fields' => :'remote_fields',
        :'ssn' => :'ssn',
        :'marital_status' => :'marital_status',
        :'termination_date' => :'termination_date',
        :'tax_id' => :'tax_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'first_name' => :'String',
        :'last_name' => :'String',
        :'work_email' => :'String',
        :'gender' => :'String',
        :'job_title' => :'String',
        :'home_address' => :'PostHrisEmployeesRequestBodyHomeAddress',
        :'date_of_birth' => :'Time',
        :'mobile_phone_number' => :'String',
        :'home_phone_number' => :'String',
        :'nationality' => :'String',
        :'start_date' => :'Time',
        :'legal_entity_id' => :'String',
        :'location_id' => :'String',
        :'remote_fields' => :'PostHrisEmployeesRequestBodyRemoteFields',
        :'ssn' => :'String',
        :'marital_status' => :'String',
        :'termination_date' => :'Time',
        :'tax_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::PatchHrisEmployeesEmployeeIdRequestBody` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::PatchHrisEmployeesEmployeeIdRequestBody`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'first_name')
        self.first_name = attributes[:'first_name']
      end

      if attributes.key?(:'last_name')
        self.last_name = attributes[:'last_name']
      end

      if attributes.key?(:'work_email')
        self.work_email = attributes[:'work_email']
      else
        self.work_email = nil
      end

      if attributes.key?(:'gender')
        self.gender = attributes[:'gender']
      end

      if attributes.key?(:'job_title')
        self.job_title = attributes[:'job_title']
      end

      if attributes.key?(:'home_address')
        self.home_address = attributes[:'home_address']
      end

      if attributes.key?(:'date_of_birth')
        self.date_of_birth = attributes[:'date_of_birth']
      end

      if attributes.key?(:'mobile_phone_number')
        self.mobile_phone_number = attributes[:'mobile_phone_number']
      end

      if attributes.key?(:'home_phone_number')
        self.home_phone_number = attributes[:'home_phone_number']
      end

      if attributes.key?(:'nationality')
        self.nationality = attributes[:'nationality']
      end

      if attributes.key?(:'start_date')
        self.start_date = attributes[:'start_date']
      end

      if attributes.key?(:'legal_entity_id')
        self.legal_entity_id = attributes[:'legal_entity_id']
      end

      if attributes.key?(:'location_id')
        self.location_id = attributes[:'location_id']
      end

      if attributes.key?(:'remote_fields')
        self.remote_fields = attributes[:'remote_fields']
      end

      if attributes.key?(:'ssn')
        self.ssn = attributes[:'ssn']
      end

      if attributes.key?(:'marital_status')
        self.marital_status = attributes[:'marital_status']
      end

      if attributes.key?(:'termination_date')
        self.termination_date = attributes[:'termination_date']
      end

      if attributes.key?(:'tax_id')
        self.tax_id = attributes[:'tax_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @work_email.nil?
        invalid_properties.push('invalid value for "work_email", work_email cannot be nil.')
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      if !@date_of_birth.nil? && @date_of_birth !~ pattern
        invalid_properties.push("invalid value for \"date_of_birth\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^[A-Z]{2}$/)
      if !@nationality.nil? && @nationality !~ pattern
        invalid_properties.push("invalid value for \"nationality\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      if !@start_date.nil? && @start_date !~ pattern
        invalid_properties.push("invalid value for \"start_date\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      if !@termination_date.nil? && @termination_date !~ pattern
        invalid_properties.push("invalid value for \"termination_date\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @work_email.nil?
      gender_validator = EnumAttributeValidator.new('String', ["MALE", "FEMALE", "NON_BINARY", "NOT_SPECIFIED"])
      return false unless gender_validator.valid?(@gender)
      return false if !@date_of_birth.nil? && @date_of_birth !~ Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      return false if !@nationality.nil? && @nationality !~ Regexp.new(/^[A-Z]{2}$/)
      return false if !@start_date.nil? && @start_date !~ Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      marital_status_validator = EnumAttributeValidator.new('String', ["SINGLE", "MARRIED", "DOMESTIC_PARTNERSHIP", "WIDOWED", "DIVORCED", "SEPARATED", "NOT_MARRIED"])
      return false unless marital_status_validator.valid?(@marital_status)
      return false if !@termination_date.nil? && @termination_date !~ Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] work_email Value to be assigned
    def work_email=(work_email)
      if work_email.nil?
        fail ArgumentError, 'work_email cannot be nil'
      end

      @work_email = work_email
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] gender Object to be assigned
    def gender=(gender)
      validator = EnumAttributeValidator.new('String', ["MALE", "FEMALE", "NON_BINARY", "NOT_SPECIFIED"])
      unless validator.valid?(gender)
        fail ArgumentError, "invalid value for \"gender\", must be one of #{validator.allowable_values}."
      end
      @gender = gender
    end

    # Custom attribute writer method with validation
    # @param [Object] date_of_birth Value to be assigned
    def date_of_birth=(date_of_birth)
      if date_of_birth.nil?
        fail ArgumentError, 'date_of_birth cannot be nil'
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      if date_of_birth !~ pattern
        fail ArgumentError, "invalid value for \"date_of_birth\", must conform to the pattern #{pattern}."
      end

      @date_of_birth = date_of_birth
    end

    # Custom attribute writer method with validation
    # @param [Object] nationality Value to be assigned
    def nationality=(nationality)
      if nationality.nil?
        fail ArgumentError, 'nationality cannot be nil'
      end

      pattern = Regexp.new(/^[A-Z]{2}$/)
      if nationality !~ pattern
        fail ArgumentError, "invalid value for \"nationality\", must conform to the pattern #{pattern}."
      end

      @nationality = nationality
    end

    # Custom attribute writer method with validation
    # @param [Object] start_date Value to be assigned
    def start_date=(start_date)
      if start_date.nil?
        fail ArgumentError, 'start_date cannot be nil'
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      if start_date !~ pattern
        fail ArgumentError, "invalid value for \"start_date\", must conform to the pattern #{pattern}."
      end

      @start_date = start_date
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] marital_status Object to be assigned
    def marital_status=(marital_status)
      validator = EnumAttributeValidator.new('String', ["SINGLE", "MARRIED", "DOMESTIC_PARTNERSHIP", "WIDOWED", "DIVORCED", "SEPARATED", "NOT_MARRIED"])
      unless validator.valid?(marital_status)
        fail ArgumentError, "invalid value for \"marital_status\", must be one of #{validator.allowable_values}."
      end
      @marital_status = marital_status
    end

    # Custom attribute writer method with validation
    # @param [Object] termination_date Value to be assigned
    def termination_date=(termination_date)
      if termination_date.nil?
        fail ArgumentError, 'termination_date cannot be nil'
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      if termination_date !~ pattern
        fail ArgumentError, "invalid value for \"termination_date\", must conform to the pattern #{pattern}."
      end

      @termination_date = termination_date
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          first_name == o.first_name &&
          last_name == o.last_name &&
          work_email == o.work_email &&
          gender == o.gender &&
          job_title == o.job_title &&
          home_address == o.home_address &&
          date_of_birth == o.date_of_birth &&
          mobile_phone_number == o.mobile_phone_number &&
          home_phone_number == o.home_phone_number &&
          nationality == o.nationality &&
          start_date == o.start_date &&
          legal_entity_id == o.legal_entity_id &&
          location_id == o.location_id &&
          remote_fields == o.remote_fields &&
          ssn == o.ssn &&
          marital_status == o.marital_status &&
          termination_date == o.termination_date &&
          tax_id == o.tax_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [first_name, last_name, work_email, gender, job_title, home_address, date_of_birth, mobile_phone_number, home_phone_number, nationality, start_date, legal_entity_id, location_id, remote_fields, ssn, marital_status, termination_date, tax_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
