=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  class PostAtsCandidatesRequestBodyCandidate < ApiModelBase
    # The first name of the candidate.
    attr_accessor :first_name

    # The last name of the candidate.
    attr_accessor :last_name

    # The primary email address this application will be created with.
    attr_accessor :email_address

    attr_accessor :additional_email_addresses

    # The company where the candidate is currently working.
    attr_accessor :company

    # The current job title of the candidate.
    attr_accessor :title

    # The phone number of the candidate.
    attr_accessor :phone_number

    attr_accessor :additional_phone_numbers

    attr_accessor :location

    # The gender of the candidate. Must be one of `MALE`, `FEMALE`, or `OTHER`.
    attr_accessor :gender

    # The date the candidate is available to start working.
    attr_accessor :availability_date

    attr_accessor :salary_expectations

    # A list of social media links of the candidate. The links must be valid URLs.
    attr_accessor :social_links

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'first_name' => :'first_name',
        :'last_name' => :'last_name',
        :'email_address' => :'email_address',
        :'additional_email_addresses' => :'additional_email_addresses',
        :'company' => :'company',
        :'title' => :'title',
        :'phone_number' => :'phone_number',
        :'additional_phone_numbers' => :'additional_phone_numbers',
        :'location' => :'location',
        :'gender' => :'gender',
        :'availability_date' => :'availability_date',
        :'salary_expectations' => :'salary_expectations',
        :'social_links' => :'social_links'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'first_name' => :'String',
        :'last_name' => :'String',
        :'email_address' => :'String',
        :'additional_email_addresses' => :'Array<PostAtsCandidatesRequestBodyCandidateAdditionalEmailAddressesInner>',
        :'company' => :'String',
        :'title' => :'String',
        :'phone_number' => :'String',
        :'additional_phone_numbers' => :'Array<PostAtsCandidatesRequestBodyCandidateAdditionalPhoneNumbersInner>',
        :'location' => :'PostAtsCandidatesRequestBodyCandidateLocation',
        :'gender' => :'String',
        :'availability_date' => :'Time',
        :'salary_expectations' => :'PostAtsCandidatesRequestBodyCandidateSalaryExpectations',
        :'social_links' => :'Array<PostAtsCandidatesRequestBodyCandidateSocialLinksInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::PostAtsCandidatesRequestBodyCandidate` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::PostAtsCandidatesRequestBodyCandidate`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'first_name')
        self.first_name = attributes[:'first_name']
      else
        self.first_name = nil
      end

      if attributes.key?(:'last_name')
        self.last_name = attributes[:'last_name']
      else
        self.last_name = nil
      end

      if attributes.key?(:'email_address')
        self.email_address = attributes[:'email_address']
      else
        self.email_address = nil
      end

      if attributes.key?(:'additional_email_addresses')
        if (value = attributes[:'additional_email_addresses']).is_a?(Array)
          self.additional_email_addresses = value
        end
      end

      if attributes.key?(:'company')
        self.company = attributes[:'company']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'phone_number')
        self.phone_number = attributes[:'phone_number']
      end

      if attributes.key?(:'additional_phone_numbers')
        if (value = attributes[:'additional_phone_numbers']).is_a?(Array)
          self.additional_phone_numbers = value
        end
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      end

      if attributes.key?(:'gender')
        self.gender = attributes[:'gender']
      end

      if attributes.key?(:'availability_date')
        self.availability_date = attributes[:'availability_date']
      end

      if attributes.key?(:'salary_expectations')
        self.salary_expectations = attributes[:'salary_expectations']
      end

      if attributes.key?(:'social_links')
        if (value = attributes[:'social_links']).is_a?(Array)
          self.social_links = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @first_name.nil?
        invalid_properties.push('invalid value for "first_name", first_name cannot be nil.')
      end

      if @last_name.nil?
        invalid_properties.push('invalid value for "last_name", last_name cannot be nil.')
      end

      if @email_address.nil?
        invalid_properties.push('invalid value for "email_address", email_address cannot be nil.')
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      if !@availability_date.nil? && @availability_date !~ pattern
        invalid_properties.push("invalid value for \"availability_date\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @first_name.nil?
      return false if @last_name.nil?
      return false if @email_address.nil?
      gender_validator = EnumAttributeValidator.new('String', ["MALE", "FEMALE", "OTHER"])
      return false unless gender_validator.valid?(@gender)
      return false if !@availability_date.nil? && @availability_date !~ Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] first_name Value to be assigned
    def first_name=(first_name)
      if first_name.nil?
        fail ArgumentError, 'first_name cannot be nil'
      end

      @first_name = first_name
    end

    # Custom attribute writer method with validation
    # @param [Object] last_name Value to be assigned
    def last_name=(last_name)
      if last_name.nil?
        fail ArgumentError, 'last_name cannot be nil'
      end

      @last_name = last_name
    end

    # Custom attribute writer method with validation
    # @param [Object] email_address Value to be assigned
    def email_address=(email_address)
      if email_address.nil?
        fail ArgumentError, 'email_address cannot be nil'
      end

      @email_address = email_address
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] gender Object to be assigned
    def gender=(gender)
      validator = EnumAttributeValidator.new('String', ["MALE", "FEMALE", "OTHER"])
      unless validator.valid?(gender)
        fail ArgumentError, "invalid value for \"gender\", must be one of #{validator.allowable_values}."
      end
      @gender = gender
    end

    # Custom attribute writer method with validation
    # @param [Object] availability_date Value to be assigned
    def availability_date=(availability_date)
      if availability_date.nil?
        fail ArgumentError, 'availability_date cannot be nil'
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      if availability_date !~ pattern
        fail ArgumentError, "invalid value for \"availability_date\", must conform to the pattern #{pattern}."
      end

      @availability_date = availability_date
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          first_name == o.first_name &&
          last_name == o.last_name &&
          email_address == o.email_address &&
          additional_email_addresses == o.additional_email_addresses &&
          company == o.company &&
          title == o.title &&
          phone_number == o.phone_number &&
          additional_phone_numbers == o.additional_phone_numbers &&
          location == o.location &&
          gender == o.gender &&
          availability_date == o.availability_date &&
          salary_expectations == o.salary_expectations &&
          social_links == o.social_links
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [first_name, last_name, email_address, additional_email_addresses, company, title, phone_number, additional_phone_numbers, location, gender, availability_date, salary_expectations, social_links].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
