=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  # Fields specific to Dayforce.
  class PostHrisEmployeesRequestBodyRemoteFieldsDayforce < ApiModelBase
    # The social security number of the employee
    attr_accessor :social_security_number

    # The pay type of the employee. This needs to be a valid XRefCode from Dayforce.
    attr_accessor :pay_type

    # The pay class of the employee. This needs to be a valid XRefCode from Dayforce.
    attr_accessor :pay_class

    # The pay group of the employee. This needs to be a valid XRefCode from Dayforce.
    attr_accessor :pay_group

    # The base rate of the employee.
    attr_accessor :base_rate

    # The role of the employee. This needs to be a valid XRefCode from Dayforce.
    attr_accessor :role

    # The location of the employee. This needs to be a valid XRefCode from Dayforce.
    attr_accessor :location

    # The department of the employee. This needs to be a valid XRefCode from Dayforce.
    attr_accessor :department

    # The job of the employee. This needs to be a valid XRefCode from Dayforce.
    attr_accessor :job

    # The country of the employee. This needs to be a valid XRefCode from Dayforce.
    attr_accessor :country

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'social_security_number' => :'social_security_number',
        :'pay_type' => :'pay_type',
        :'pay_class' => :'pay_class',
        :'pay_group' => :'pay_group',
        :'base_rate' => :'base_rate',
        :'role' => :'role',
        :'location' => :'location',
        :'department' => :'department',
        :'job' => :'job',
        :'country' => :'country'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'social_security_number' => :'String',
        :'pay_type' => :'String',
        :'pay_class' => :'String',
        :'pay_group' => :'String',
        :'base_rate' => :'Float',
        :'role' => :'String',
        :'location' => :'String',
        :'department' => :'String',
        :'job' => :'String',
        :'country' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::PostHrisEmployeesRequestBodyRemoteFieldsDayforce` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::PostHrisEmployeesRequestBodyRemoteFieldsDayforce`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'social_security_number')
        self.social_security_number = attributes[:'social_security_number']
      else
        self.social_security_number = nil
      end

      if attributes.key?(:'pay_type')
        self.pay_type = attributes[:'pay_type']
      else
        self.pay_type = nil
      end

      if attributes.key?(:'pay_class')
        self.pay_class = attributes[:'pay_class']
      else
        self.pay_class = nil
      end

      if attributes.key?(:'pay_group')
        self.pay_group = attributes[:'pay_group']
      else
        self.pay_group = nil
      end

      if attributes.key?(:'base_rate')
        self.base_rate = attributes[:'base_rate']
      else
        self.base_rate = nil
      end

      if attributes.key?(:'role')
        self.role = attributes[:'role']
      else
        self.role = nil
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      else
        self.location = nil
      end

      if attributes.key?(:'department')
        self.department = attributes[:'department']
      else
        self.department = nil
      end

      if attributes.key?(:'job')
        self.job = attributes[:'job']
      else
        self.job = nil
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      else
        self.country = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @social_security_number.nil?
        invalid_properties.push('invalid value for "social_security_number", social_security_number cannot be nil.')
      end

      if @pay_type.nil?
        invalid_properties.push('invalid value for "pay_type", pay_type cannot be nil.')
      end

      if @pay_class.nil?
        invalid_properties.push('invalid value for "pay_class", pay_class cannot be nil.')
      end

      if @pay_group.nil?
        invalid_properties.push('invalid value for "pay_group", pay_group cannot be nil.')
      end

      if @base_rate.nil?
        invalid_properties.push('invalid value for "base_rate", base_rate cannot be nil.')
      end

      if @base_rate < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        invalid_properties.push('invalid value for "base_rate", must be greater than or equal to -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.')
      end

      if @role.nil?
        invalid_properties.push('invalid value for "role", role cannot be nil.')
      end

      if @location.nil?
        invalid_properties.push('invalid value for "location", location cannot be nil.')
      end

      if @department.nil?
        invalid_properties.push('invalid value for "department", department cannot be nil.')
      end

      if @job.nil?
        invalid_properties.push('invalid value for "job", job cannot be nil.')
      end

      if @country.nil?
        invalid_properties.push('invalid value for "country", country cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @social_security_number.nil?
      return false if @pay_type.nil?
      return false if @pay_class.nil?
      return false if @pay_group.nil?
      return false if @base_rate.nil?
      return false if @base_rate < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
      return false if @role.nil?
      return false if @location.nil?
      return false if @department.nil?
      return false if @job.nil?
      return false if @country.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] social_security_number Value to be assigned
    def social_security_number=(social_security_number)
      if social_security_number.nil?
        fail ArgumentError, 'social_security_number cannot be nil'
      end

      @social_security_number = social_security_number
    end

    # Custom attribute writer method with validation
    # @param [Object] pay_type Value to be assigned
    def pay_type=(pay_type)
      if pay_type.nil?
        fail ArgumentError, 'pay_type cannot be nil'
      end

      @pay_type = pay_type
    end

    # Custom attribute writer method with validation
    # @param [Object] pay_class Value to be assigned
    def pay_class=(pay_class)
      if pay_class.nil?
        fail ArgumentError, 'pay_class cannot be nil'
      end

      @pay_class = pay_class
    end

    # Custom attribute writer method with validation
    # @param [Object] pay_group Value to be assigned
    def pay_group=(pay_group)
      if pay_group.nil?
        fail ArgumentError, 'pay_group cannot be nil'
      end

      @pay_group = pay_group
    end

    # Custom attribute writer method with validation
    # @param [Object] base_rate Value to be assigned
    def base_rate=(base_rate)
      if base_rate.nil?
        fail ArgumentError, 'base_rate cannot be nil'
      end

      if base_rate < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        fail ArgumentError, 'invalid value for "base_rate", must be greater than or equal to -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.'
      end

      @base_rate = base_rate
    end

    # Custom attribute writer method with validation
    # @param [Object] role Value to be assigned
    def role=(role)
      if role.nil?
        fail ArgumentError, 'role cannot be nil'
      end

      @role = role
    end

    # Custom attribute writer method with validation
    # @param [Object] location Value to be assigned
    def location=(location)
      if location.nil?
        fail ArgumentError, 'location cannot be nil'
      end

      @location = location
    end

    # Custom attribute writer method with validation
    # @param [Object] department Value to be assigned
    def department=(department)
      if department.nil?
        fail ArgumentError, 'department cannot be nil'
      end

      @department = department
    end

    # Custom attribute writer method with validation
    # @param [Object] job Value to be assigned
    def job=(job)
      if job.nil?
        fail ArgumentError, 'job cannot be nil'
      end

      @job = job
    end

    # Custom attribute writer method with validation
    # @param [Object] country Value to be assigned
    def country=(country)
      if country.nil?
        fail ArgumentError, 'country cannot be nil'
      end

      @country = country
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          social_security_number == o.social_security_number &&
          pay_type == o.pay_type &&
          pay_class == o.pay_class &&
          pay_group == o.pay_group &&
          base_rate == o.base_rate &&
          role == o.role &&
          location == o.location &&
          department == o.department &&
          job == o.job &&
          country == o.country
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [social_security_number, pay_type, pay_class, pay_group, base_rate, role, location, department, job, country].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
