=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  # Fields specific to SAP SuccessFactors.
  class PostAtsCandidatesRequestBodyRemoteFieldsAllOfSuccessfactors < ApiModelBase
    # Fields that we will pass through to SuccessFactor's `Candidate` object.
    attr_accessor :candidate

    # Fields that we will pass through to SuccessFactor's `JobApplication` object.
    attr_accessor :job_application

    # If set to true, we will copy custom attachments from the JobApplication to the Candidate.
    attr_accessor :copy_job_application_attachments

    # When the candidate already exists, whether to update the Candidate with the remote fields found under the Candidate entity.
    attr_accessor :update_existing_candidate

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'candidate' => :'Candidate',
        :'job_application' => :'JobApplication',
        :'copy_job_application_attachments' => :'copyJobApplicationAttachments',
        :'update_existing_candidate' => :'update_existing_candidate'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'candidate' => :'Hash<String, Object>',
        :'job_application' => :'Hash<String, Object>',
        :'copy_job_application_attachments' => :'Boolean',
        :'update_existing_candidate' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'update_existing_candidate'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::PostAtsCandidatesRequestBodyRemoteFieldsAllOfSuccessfactors` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::PostAtsCandidatesRequestBodyRemoteFieldsAllOfSuccessfactors`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'candidate')
        if (value = attributes[:'candidate']).is_a?(Hash)
          self.candidate = value
        end
      end

      if attributes.key?(:'job_application')
        if (value = attributes[:'job_application']).is_a?(Hash)
          self.job_application = value
        end
      end

      if attributes.key?(:'copy_job_application_attachments')
        self.copy_job_application_attachments = attributes[:'copy_job_application_attachments']
      end

      if attributes.key?(:'update_existing_candidate')
        self.update_existing_candidate = attributes[:'update_existing_candidate']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          candidate == o.candidate &&
          job_application == o.job_application &&
          copy_job_application_attachments == o.copy_job_application_attachments &&
          update_existing_candidate == o.update_existing_candidate
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [candidate, job_application, copy_job_application_attachments, update_existing_candidate].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
