=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  class PostAtsCandidatesRequestBodyRemoteFieldsAllOfWorkdayCandidateDataJobApplicationDataResumeDataEducationDataInner < ApiModelBase
    attr_accessor :school_name

    attr_accessor :first_year_attended

    attr_accessor :last_year_attended

    attr_accessor :field_of_study_reference

    attr_accessor :degree_reference

    attr_accessor :grade_average

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'school_name' => :'School_Name',
        :'first_year_attended' => :'First_Year_Attended',
        :'last_year_attended' => :'Last_Year_Attended',
        :'field_of_study_reference' => :'Field_of_Study_Reference',
        :'degree_reference' => :'Degree_Reference',
        :'grade_average' => :'Grade_Average'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'school_name' => :'String',
        :'first_year_attended' => :'Float',
        :'last_year_attended' => :'Float',
        :'field_of_study_reference' => :'PostAtsCandidatesRequestBodyRemoteFieldsAllOfWorkdayCandidateDataJobApplicationDataResumeDataEducationDataInnerFieldOfStudyReference',
        :'degree_reference' => :'PostAtsCandidatesRequestBodyRemoteFieldsAllOfWorkdayCandidateDataJobApplicationDataResumeDataEducationDataInnerFieldOfStudyReference',
        :'grade_average' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::PostAtsCandidatesRequestBodyRemoteFieldsAllOfWorkdayCandidateDataJobApplicationDataResumeDataEducationDataInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::PostAtsCandidatesRequestBodyRemoteFieldsAllOfWorkdayCandidateDataJobApplicationDataResumeDataEducationDataInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'school_name')
        self.school_name = attributes[:'school_name']
      end

      if attributes.key?(:'first_year_attended')
        self.first_year_attended = attributes[:'first_year_attended']
      end

      if attributes.key?(:'last_year_attended')
        self.last_year_attended = attributes[:'last_year_attended']
      end

      if attributes.key?(:'field_of_study_reference')
        self.field_of_study_reference = attributes[:'field_of_study_reference']
      end

      if attributes.key?(:'degree_reference')
        self.degree_reference = attributes[:'degree_reference']
      end

      if attributes.key?(:'grade_average')
        self.grade_average = attributes[:'grade_average']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@first_year_attended.nil? && @first_year_attended < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        invalid_properties.push('invalid value for "first_year_attended", must be greater than or equal to -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.')
      end

      if !@last_year_attended.nil? && @last_year_attended < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        invalid_properties.push('invalid value for "last_year_attended", must be greater than or equal to -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@first_year_attended.nil? && @first_year_attended < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
      return false if !@last_year_attended.nil? && @last_year_attended < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] first_year_attended Value to be assigned
    def first_year_attended=(first_year_attended)
      if first_year_attended.nil?
        fail ArgumentError, 'first_year_attended cannot be nil'
      end

      if first_year_attended < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        fail ArgumentError, 'invalid value for "first_year_attended", must be greater than or equal to -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.'
      end

      @first_year_attended = first_year_attended
    end

    # Custom attribute writer method with validation
    # @param [Object] last_year_attended Value to be assigned
    def last_year_attended=(last_year_attended)
      if last_year_attended.nil?
        fail ArgumentError, 'last_year_attended cannot be nil'
      end

      if last_year_attended < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        fail ArgumentError, 'invalid value for "last_year_attended", must be greater than or equal to -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.'
      end

      @last_year_attended = last_year_attended
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          school_name == o.school_name &&
          first_year_attended == o.first_year_attended &&
          last_year_attended == o.last_year_attended &&
          field_of_study_reference == o.field_of_study_reference &&
          degree_reference == o.degree_reference &&
          grade_average == o.grade_average
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [school_name, first_year_attended, last_year_attended, field_of_study_reference, degree_reference, grade_average].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
