=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  # The data to request an electronic certificate of incapacity for work (eAU).
  class PostCustomDatevEmployeesEmployeeIdEauRequestsRequestBody < ApiModelBase
    # Date \"start_work_incapacity\" from the original eAU-Request.
    attr_accessor :start_work_incapacity

    attr_accessor :notification

    attr_accessor :contact_person

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'start_work_incapacity' => :'start_work_incapacity',
        :'notification' => :'notification',
        :'contact_person' => :'contact_person'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'start_work_incapacity' => :'String',
        :'notification' => :'PostCustomDatevEmployeesEmployeeIdEauRequestsRequestBodyNotification',
        :'contact_person' => :'PostCustomDatevEmployeesEmployeeIdEauRequestsRequestBodyContactPerson'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::PostCustomDatevEmployeesEmployeeIdEauRequestsRequestBody` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::PostCustomDatevEmployeesEmployeeIdEauRequestsRequestBody`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'start_work_incapacity')
        self.start_work_incapacity = attributes[:'start_work_incapacity']
      else
        self.start_work_incapacity = nil
      end

      if attributes.key?(:'notification')
        self.notification = attributes[:'notification']
      end

      if attributes.key?(:'contact_person')
        self.contact_person = attributes[:'contact_person']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @start_work_incapacity.nil?
        invalid_properties.push('invalid value for "start_work_incapacity", start_work_incapacity cannot be nil.')
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}$/)
      if @start_work_incapacity !~ pattern
        invalid_properties.push("invalid value for \"start_work_incapacity\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @start_work_incapacity.nil?
      return false if @start_work_incapacity !~ Regexp.new(/^\d{4}-\d{2}-\d{2}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] start_work_incapacity Value to be assigned
    def start_work_incapacity=(start_work_incapacity)
      if start_work_incapacity.nil?
        fail ArgumentError, 'start_work_incapacity cannot be nil'
      end

      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}$/)
      if start_work_incapacity !~ pattern
        fail ArgumentError, "invalid value for \"start_work_incapacity\", must conform to the pattern #{pattern}."
      end

      @start_work_incapacity = start_work_incapacity
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          start_work_incapacity == o.start_work_incapacity &&
          notification == o.notification &&
          contact_person == o.contact_person
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [start_work_incapacity, notification, contact_person].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
