=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  class PostAtsJobsJobIdApplicationsPositiveResponseData < ApiModelBase
    # The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
    attr_accessor :id

    # The raw ID of the object in the remote system. We don't recommend using this as a primary key on your side as it might sometimes be compromised of multiple identifiers if a system doesn't provide a clear primary key.
    attr_accessor :remote_id

    # Parsed status of the application. If Kombo identifies that the application was accepted and the candidate hired, it will be `HIRED`. If the application was rejected or the candidate declined, it will be `DECLINED`. If the application is still in process, it will be `PENDING`. Kombo will always try to deliver this information as reliably as possible.
    attr_accessor :outcome

    # Reason for the rejection of the candidate.
    attr_accessor :rejection_reason_name

    # The time that the application was rejected.
    attr_accessor :rejected_at

    # ID of the current application stage
    attr_accessor :current_stage_id

    # The Kombo ID of the job which the candidate applied to. The ID can be used to retrieve the job from the `get jobs` endpoint.
    attr_accessor :job_id

    # The Kombo ID of the candidate who applied to the job. The ID can be used to retrieve the candidate from the `get candidates` endpoint.
    attr_accessor :candidate_id

    # A list of answers to screening questions. The screening answer type `FILE` is currently unsupported.
    attr_accessor :screening_question_answers

    # A key-value store of fields not covered by the schema. [Read more](/custom-fields)
    attr_accessor :custom_fields

    # An array of selected passthrough integration fields. [Read more](/integration-fields)
    attr_accessor :integration_fields

    # URL to the application in the source ATS system. When embedding this in your system, please consider that not for all ATS a dedicated application URL is available, so you might need to fall back to the candidate URL.
    attr_accessor :remote_url

    # The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
    attr_accessor :changed_at

    # The date and time the object was deleted in the remote system. Objects are automatically marked as deleted when Kombo can't retrieve them from the remote system anymore. Kombo will also anonymize entries 14 days after they disappear.
    attr_accessor :remote_deleted_at

    # The date and time the object was created in the remote system.
    attr_accessor :remote_created_at

    # A timestamp retrieved from the remote system, describing when the resource was last updated.
    attr_accessor :remote_updated_at

    # Includes the data fetched from the remote system. Please be aware that including this in you scope config might violate other scopes that are set.  Remote data always has the endpoint path that we got the data from as the top level key. For example, it could look like: `{ \"/companies\": { ... }}`  This is not available on all plans. Reach out to Kombo if you need it.
    attr_accessor :remote_data

    attr_accessor :current_stage

    attr_accessor :job

    attr_accessor :candidate

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'remote_id' => :'remote_id',
        :'outcome' => :'outcome',
        :'rejection_reason_name' => :'rejection_reason_name',
        :'rejected_at' => :'rejected_at',
        :'current_stage_id' => :'current_stage_id',
        :'job_id' => :'job_id',
        :'candidate_id' => :'candidate_id',
        :'screening_question_answers' => :'screening_question_answers',
        :'custom_fields' => :'custom_fields',
        :'integration_fields' => :'integration_fields',
        :'remote_url' => :'remote_url',
        :'changed_at' => :'changed_at',
        :'remote_deleted_at' => :'remote_deleted_at',
        :'remote_created_at' => :'remote_created_at',
        :'remote_updated_at' => :'remote_updated_at',
        :'remote_data' => :'remote_data',
        :'current_stage' => :'current_stage',
        :'job' => :'job',
        :'candidate' => :'candidate'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'remote_id' => :'String',
        :'outcome' => :'String',
        :'rejection_reason_name' => :'String',
        :'rejected_at' => :'Time',
        :'current_stage_id' => :'String',
        :'job_id' => :'String',
        :'candidate_id' => :'String',
        :'screening_question_answers' => :'Array<GetAtsApplicationsPositiveResponseDataResultsInnerScreeningQuestionAnswersInner>',
        :'custom_fields' => :'Hash<String, Object>',
        :'integration_fields' => :'Array<GetHrisEmployeesPositiveResponseDataResultsInnerIntegrationFieldsInner>',
        :'remote_url' => :'String',
        :'changed_at' => :'Time',
        :'remote_deleted_at' => :'Time',
        :'remote_created_at' => :'Time',
        :'remote_updated_at' => :'Time',
        :'remote_data' => :'Hash<String, Object>',
        :'current_stage' => :'GetAtsApplicationsPositiveResponseDataResultsInnerCurrentStage',
        :'job' => :'GetAtsApplicationsPositiveResponseDataResultsInnerJob',
        :'candidate' => :'PostAtsJobsJobIdApplicationsPositiveResponseDataCandidate'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'remote_id',
        :'outcome',
        :'rejection_reason_name',
        :'rejected_at',
        :'current_stage_id',
        :'job_id',
        :'candidate_id',
        :'screening_question_answers',
        :'custom_fields',
        :'remote_url',
        :'remote_deleted_at',
        :'remote_created_at',
        :'remote_updated_at',
        :'remote_data',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::PostAtsJobsJobIdApplicationsPositiveResponseData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::PostAtsJobsJobIdApplicationsPositiveResponseData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'remote_id')
        self.remote_id = attributes[:'remote_id']
      else
        self.remote_id = nil
      end

      if attributes.key?(:'outcome')
        self.outcome = attributes[:'outcome']
      else
        self.outcome = nil
      end

      if attributes.key?(:'rejection_reason_name')
        self.rejection_reason_name = attributes[:'rejection_reason_name']
      else
        self.rejection_reason_name = nil
      end

      if attributes.key?(:'rejected_at')
        self.rejected_at = attributes[:'rejected_at']
      else
        self.rejected_at = nil
      end

      if attributes.key?(:'current_stage_id')
        self.current_stage_id = attributes[:'current_stage_id']
      else
        self.current_stage_id = nil
      end

      if attributes.key?(:'job_id')
        self.job_id = attributes[:'job_id']
      else
        self.job_id = nil
      end

      if attributes.key?(:'candidate_id')
        self.candidate_id = attributes[:'candidate_id']
      else
        self.candidate_id = nil
      end

      if attributes.key?(:'screening_question_answers')
        if (value = attributes[:'screening_question_answers']).is_a?(Array)
          self.screening_question_answers = value
        end
      end

      if attributes.key?(:'custom_fields')
        if (value = attributes[:'custom_fields']).is_a?(Hash)
          self.custom_fields = value
        end
      else
        self.custom_fields = nil
      end

      if attributes.key?(:'integration_fields')
        if (value = attributes[:'integration_fields']).is_a?(Array)
          self.integration_fields = value
        end
      else
        self.integration_fields = nil
      end

      if attributes.key?(:'remote_url')
        self.remote_url = attributes[:'remote_url']
      else
        self.remote_url = nil
      end

      if attributes.key?(:'changed_at')
        self.changed_at = attributes[:'changed_at']
      else
        self.changed_at = nil
      end

      if attributes.key?(:'remote_deleted_at')
        self.remote_deleted_at = attributes[:'remote_deleted_at']
      else
        self.remote_deleted_at = nil
      end

      if attributes.key?(:'remote_created_at')
        self.remote_created_at = attributes[:'remote_created_at']
      else
        self.remote_created_at = nil
      end

      if attributes.key?(:'remote_updated_at')
        self.remote_updated_at = attributes[:'remote_updated_at']
      else
        self.remote_updated_at = nil
      end

      if attributes.key?(:'remote_data')
        if (value = attributes[:'remote_data']).is_a?(Hash)
          self.remote_data = value
        end
      else
        self.remote_data = nil
      end

      if attributes.key?(:'current_stage')
        self.current_stage = attributes[:'current_stage']
      else
        self.current_stage = nil
      end

      if attributes.key?(:'job')
        self.job = attributes[:'job']
      else
        self.job = nil
      end

      if attributes.key?(:'candidate')
        self.candidate = attributes[:'candidate']
      else
        self.candidate = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @integration_fields.nil?
        invalid_properties.push('invalid value for "integration_fields", integration_fields cannot be nil.')
      end

      if @changed_at.nil?
        invalid_properties.push('invalid value for "changed_at", changed_at cannot be nil.')
      end

      if @current_stage.nil?
        invalid_properties.push('invalid value for "current_stage", current_stage cannot be nil.')
      end

      if @job.nil?
        invalid_properties.push('invalid value for "job", job cannot be nil.')
      end

      if @candidate.nil?
        invalid_properties.push('invalid value for "candidate", candidate cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      outcome_validator = EnumAttributeValidator.new('String', ["PENDING", "HIRED", "DECLINED"])
      return false unless outcome_validator.valid?(@outcome)
      return false if @integration_fields.nil?
      return false if @changed_at.nil?
      return false if @current_stage.nil?
      return false if @job.nil?
      return false if @candidate.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] outcome Object to be assigned
    def outcome=(outcome)
      validator = EnumAttributeValidator.new('String', ["PENDING", "HIRED", "DECLINED"])
      unless validator.valid?(outcome)
        fail ArgumentError, "invalid value for \"outcome\", must be one of #{validator.allowable_values}."
      end
      @outcome = outcome
    end

    # Custom attribute writer method with validation
    # @param [Object] integration_fields Value to be assigned
    def integration_fields=(integration_fields)
      if integration_fields.nil?
        fail ArgumentError, 'integration_fields cannot be nil'
      end

      @integration_fields = integration_fields
    end

    # Custom attribute writer method with validation
    # @param [Object] changed_at Value to be assigned
    def changed_at=(changed_at)
      if changed_at.nil?
        fail ArgumentError, 'changed_at cannot be nil'
      end

      @changed_at = changed_at
    end

    # Custom attribute writer method with validation
    # @param [Object] current_stage Value to be assigned
    def current_stage=(current_stage)
      if current_stage.nil?
        fail ArgumentError, 'current_stage cannot be nil'
      end

      @current_stage = current_stage
    end

    # Custom attribute writer method with validation
    # @param [Object] job Value to be assigned
    def job=(job)
      if job.nil?
        fail ArgumentError, 'job cannot be nil'
      end

      @job = job
    end

    # Custom attribute writer method with validation
    # @param [Object] candidate Value to be assigned
    def candidate=(candidate)
      if candidate.nil?
        fail ArgumentError, 'candidate cannot be nil'
      end

      @candidate = candidate
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          remote_id == o.remote_id &&
          outcome == o.outcome &&
          rejection_reason_name == o.rejection_reason_name &&
          rejected_at == o.rejected_at &&
          current_stage_id == o.current_stage_id &&
          job_id == o.job_id &&
          candidate_id == o.candidate_id &&
          screening_question_answers == o.screening_question_answers &&
          custom_fields == o.custom_fields &&
          integration_fields == o.integration_fields &&
          remote_url == o.remote_url &&
          changed_at == o.changed_at &&
          remote_deleted_at == o.remote_deleted_at &&
          remote_created_at == o.remote_created_at &&
          remote_updated_at == o.remote_updated_at &&
          remote_data == o.remote_data &&
          current_stage == o.current_stage &&
          job == o.job &&
          candidate == o.candidate
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, remote_id, outcome, rejection_reason_name, rejected_at, current_stage_id, job_id, candidate_id, screening_question_answers, custom_fields, integration_fields, remote_url, changed_at, remote_deleted_at, remote_created_at, remote_updated_at, remote_data, current_stage, job, candidate].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
