=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  class PostLmsProgressPositiveResponseData < ApiModelBase
    # The Kombo ID of the progress entry.
    attr_accessor :id

    # The remote ID of the progress entry.
    attr_accessor :remote_id

    # The ID of the course this progress relates to.
    attr_accessor :course_id

    # The ID of the user this progress belongs to.
    attr_accessor :user_id

    # Current status of the learner in this course.
    attr_accessor :status

    # Date when the user enrolled in the course.
    attr_accessor :enrollment_date

    # Date when the user completed the course.
    attr_accessor :completion_date

    # Numerical score achieved by the user (e.g., 85.5).
    attr_accessor :score

    # Total time spent on the course in minutes.
    attr_accessor :duration

    # Additional comments or notes about the progress.
    attr_accessor :comments

    # The timestamp when this specific record was last modified. This field only updates when properties directly on this record change, NOT when related or nested models change. For filtering that considers nested data changes, use the `updated_after` parameter which will return records when either the record itself OR its related models have been updated.
    attr_accessor :changed_at

    # Includes the data fetched from the remote system. Please be aware that including this in you scope config might violate other scopes that are set.  Remote data always has the endpoint path that we got the data from as the top level key. For example, it could look like: `{ \"/companies\": { ... }}`  This is not available on all plans. Reach out to Kombo if you need it.
    attr_accessor :remote_data

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'remote_id' => :'remote_id',
        :'course_id' => :'course_id',
        :'user_id' => :'user_id',
        :'status' => :'status',
        :'enrollment_date' => :'enrollment_date',
        :'completion_date' => :'completion_date',
        :'score' => :'score',
        :'duration' => :'duration',
        :'comments' => :'comments',
        :'changed_at' => :'changed_at',
        :'remote_data' => :'remote_data'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'remote_id' => :'String',
        :'course_id' => :'String',
        :'user_id' => :'String',
        :'status' => :'String',
        :'enrollment_date' => :'String',
        :'completion_date' => :'String',
        :'score' => :'Float',
        :'duration' => :'Float',
        :'comments' => :'String',
        :'changed_at' => :'Time',
        :'remote_data' => :'Hash<String, Object>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'enrollment_date',
        :'completion_date',
        :'score',
        :'duration',
        :'comments',
        :'remote_data'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::PostLmsProgressPositiveResponseData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::PostLmsProgressPositiveResponseData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'remote_id')
        self.remote_id = attributes[:'remote_id']
      else
        self.remote_id = nil
      end

      if attributes.key?(:'course_id')
        self.course_id = attributes[:'course_id']
      else
        self.course_id = nil
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      else
        self.user_id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'enrollment_date')
        self.enrollment_date = attributes[:'enrollment_date']
      else
        self.enrollment_date = nil
      end

      if attributes.key?(:'completion_date')
        self.completion_date = attributes[:'completion_date']
      else
        self.completion_date = nil
      end

      if attributes.key?(:'score')
        self.score = attributes[:'score']
      else
        self.score = nil
      end

      if attributes.key?(:'duration')
        self.duration = attributes[:'duration']
      else
        self.duration = nil
      end

      if attributes.key?(:'comments')
        self.comments = attributes[:'comments']
      else
        self.comments = nil
      end

      if attributes.key?(:'changed_at')
        self.changed_at = attributes[:'changed_at']
      else
        self.changed_at = nil
      end

      if attributes.key?(:'remote_data')
        if (value = attributes[:'remote_data']).is_a?(Hash)
          self.remote_data = value
        end
      else
        self.remote_data = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @remote_id.nil?
        invalid_properties.push('invalid value for "remote_id", remote_id cannot be nil.')
      end

      if @course_id.nil?
        invalid_properties.push('invalid value for "course_id", course_id cannot be nil.')
      end

      if @user_id.nil?
        invalid_properties.push('invalid value for "user_id", user_id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @score < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        invalid_properties.push('invalid value for "score", must be greater than or equal to -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.')
      end

      if @duration < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        invalid_properties.push('invalid value for "duration", must be greater than or equal to -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.')
      end

      if @changed_at.nil?
        invalid_properties.push('invalid value for "changed_at", changed_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @remote_id.nil?
      return false if @course_id.nil?
      return false if @user_id.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["ENROLLED", "STARTED", "COMPLETED", "STOPPED"])
      return false unless status_validator.valid?(@status)
      return false if @score < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
      return false if @duration < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
      return false if @changed_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] remote_id Value to be assigned
    def remote_id=(remote_id)
      if remote_id.nil?
        fail ArgumentError, 'remote_id cannot be nil'
      end

      @remote_id = remote_id
    end

    # Custom attribute writer method with validation
    # @param [Object] course_id Value to be assigned
    def course_id=(course_id)
      if course_id.nil?
        fail ArgumentError, 'course_id cannot be nil'
      end

      @course_id = course_id
    end

    # Custom attribute writer method with validation
    # @param [Object] user_id Value to be assigned
    def user_id=(user_id)
      if user_id.nil?
        fail ArgumentError, 'user_id cannot be nil'
      end

      @user_id = user_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["ENROLLED", "STARTED", "COMPLETED", "STOPPED"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] score Value to be assigned
    def score=(score)
      if !score.nil? && score < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        fail ArgumentError, 'invalid value for "score", must be greater than or equal to -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.'
      end

      @score = score
    end

    # Custom attribute writer method with validation
    # @param [Object] duration Value to be assigned
    def duration=(duration)
      if !duration.nil? && duration < -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        fail ArgumentError, 'invalid value for "duration", must be greater than or equal to -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.'
      end

      @duration = duration
    end

    # Custom attribute writer method with validation
    # @param [Object] changed_at Value to be assigned
    def changed_at=(changed_at)
      if changed_at.nil?
        fail ArgumentError, 'changed_at cannot be nil'
      end

      @changed_at = changed_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          remote_id == o.remote_id &&
          course_id == o.course_id &&
          user_id == o.user_id &&
          status == o.status &&
          enrollment_date == o.enrollment_date &&
          completion_date == o.completion_date &&
          score == o.score &&
          duration == o.duration &&
          comments == o.comments &&
          changed_at == o.changed_at &&
          remote_data == o.remote_data
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, remote_id, course_id, user_id, status, enrollment_date, completion_date, score, duration, comments, changed_at, remote_data].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
