=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  class PostHrisProvisioningGroupsGroupIdDiffPositiveResponseDataUsers < ApiModelBase
    # The users we've found in the HR systems who match the provisioning filters but haven't been provisioned in your system yet.
    attr_accessor :to_provision

    # The users who've been provisioned in your system but couldn't be found in the HR system or don't match the provisioning filters.
    attr_accessor :to_deprovision

    # The users who are in the HR system and match the provisioning filters but have already been provisioned in your system.
    attr_accessor :already_provisioned

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'to_provision' => :'to_provision',
        :'to_deprovision' => :'to_deprovision',
        :'already_provisioned' => :'already_provisioned'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'to_provision' => :'Array<PostHrisProvisioningGroupsGroupIdDiffPositiveResponseDataUsersToProvisionInner>',
        :'to_deprovision' => :'Array<PostHrisProvisioningGroupsGroupIdDiffPositiveResponseDataUsersToDeprovisionInner>',
        :'already_provisioned' => :'Array<PostHrisProvisioningGroupsGroupIdDiffPositiveResponseDataUsersAlreadyProvisionedInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::PostHrisProvisioningGroupsGroupIdDiffPositiveResponseDataUsers` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::PostHrisProvisioningGroupsGroupIdDiffPositiveResponseDataUsers`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'to_provision')
        if (value = attributes[:'to_provision']).is_a?(Array)
          self.to_provision = value
        end
      else
        self.to_provision = nil
      end

      if attributes.key?(:'to_deprovision')
        if (value = attributes[:'to_deprovision']).is_a?(Array)
          self.to_deprovision = value
        end
      else
        self.to_deprovision = nil
      end

      if attributes.key?(:'already_provisioned')
        if (value = attributes[:'already_provisioned']).is_a?(Array)
          self.already_provisioned = value
        end
      else
        self.already_provisioned = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @to_provision.nil?
        invalid_properties.push('invalid value for "to_provision", to_provision cannot be nil.')
      end

      if @to_deprovision.nil?
        invalid_properties.push('invalid value for "to_deprovision", to_deprovision cannot be nil.')
      end

      if @already_provisioned.nil?
        invalid_properties.push('invalid value for "already_provisioned", already_provisioned cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @to_provision.nil?
      return false if @to_deprovision.nil?
      return false if @already_provisioned.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] to_provision Value to be assigned
    def to_provision=(to_provision)
      if to_provision.nil?
        fail ArgumentError, 'to_provision cannot be nil'
      end

      @to_provision = to_provision
    end

    # Custom attribute writer method with validation
    # @param [Object] to_deprovision Value to be assigned
    def to_deprovision=(to_deprovision)
      if to_deprovision.nil?
        fail ArgumentError, 'to_deprovision cannot be nil'
      end

      @to_deprovision = to_deprovision
    end

    # Custom attribute writer method with validation
    # @param [Object] already_provisioned Value to be assigned
    def already_provisioned=(already_provisioned)
      if already_provisioned.nil?
        fail ArgumentError, 'already_provisioned cannot be nil'
      end

      @already_provisioned = already_provisioned
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          to_provision == o.to_provision &&
          to_deprovision == o.to_deprovision &&
          already_provisioned == o.already_provisioned
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [to_provision, to_deprovision, already_provisioned].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
