=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  class PostAtsImportTrackedApplicationRequestBody < ApiModelBase
    attr_accessor :erecruiter

    attr_accessor :successfactors

    attr_accessor :recruitee

    attr_accessor :greenhouse

    attr_accessor :onlyfy

    attr_accessor :smartrecruiters

    # YYYY-MM-DDTHH:mm:ss.sssZ
    attr_accessor :tracked_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'erecruiter' => :'erecruiter',
        :'successfactors' => :'successfactors',
        :'recruitee' => :'recruitee',
        :'greenhouse' => :'greenhouse',
        :'onlyfy' => :'onlyfy',
        :'smartrecruiters' => :'smartrecruiters',
        :'tracked_at' => :'tracked_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'erecruiter' => :'PostAtsImportTrackedApplicationPositiveResponseDataImportedIdErecruiter',
        :'successfactors' => :'PostAtsImportTrackedApplicationPositiveResponseDataImportedIdSuccessfactors',
        :'recruitee' => :'PostAtsImportTrackedApplicationPositiveResponseDataImportedIdRecruitee',
        :'greenhouse' => :'PostAtsImportTrackedApplicationPositiveResponseDataImportedIdGreenhouse',
        :'onlyfy' => :'PostAtsImportTrackedApplicationPositiveResponseDataImportedIdOnlyfy',
        :'smartrecruiters' => :'PostAtsImportTrackedApplicationPositiveResponseDataImportedIdSmartrecruiters',
        :'tracked_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'tracked_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::PostAtsImportTrackedApplicationRequestBody` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::PostAtsImportTrackedApplicationRequestBody`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'erecruiter')
        self.erecruiter = attributes[:'erecruiter']
      end

      if attributes.key?(:'successfactors')
        self.successfactors = attributes[:'successfactors']
      end

      if attributes.key?(:'recruitee')
        self.recruitee = attributes[:'recruitee']
      end

      if attributes.key?(:'greenhouse')
        self.greenhouse = attributes[:'greenhouse']
      end

      if attributes.key?(:'onlyfy')
        self.onlyfy = attributes[:'onlyfy']
      end

      if attributes.key?(:'smartrecruiters')
        self.smartrecruiters = attributes[:'smartrecruiters']
      end

      if attributes.key?(:'tracked_at')
        self.tracked_at = attributes[:'tracked_at']
      else
        self.tracked_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      if @tracked_at !~ pattern
        invalid_properties.push("invalid value for \"tracked_at\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @tracked_at !~ Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] tracked_at Value to be assigned
    def tracked_at=(tracked_at)
      pattern = Regexp.new(/^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\.\d+)?)?Z?$/)
      if !tracked_at.nil? && tracked_at !~ pattern
        fail ArgumentError, "invalid value for \"tracked_at\", must conform to the pattern #{pattern}."
      end

      @tracked_at = tracked_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          erecruiter == o.erecruiter &&
          successfactors == o.successfactors &&
          recruitee == o.recruitee &&
          greenhouse == o.greenhouse &&
          onlyfy == o.onlyfy &&
          smartrecruiters == o.smartrecruiters &&
          tracked_at == o.tracked_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [erecruiter, successfactors, recruitee, greenhouse, onlyfy, smartrecruiters, tracked_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
