=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  class PostAiApplyPostingsPostingIdInquirePositiveResponseDataApplicationFormInnerAnyOf < ApiModelBase
    attr_accessor :block_type

    # The globally unique ID of this object generated by Kombo. We recommend using this as a stable primary key for syncing.
    attr_accessor :question_id

    attr_accessor :label

    attr_accessor :description

    attr_accessor :required

    attr_accessor :category

    attr_accessor :question_type

    attr_accessor :unified_key

    attr_accessor :options

    attr_accessor :display_when

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'block_type' => :'block_type',
        :'question_id' => :'question_id',
        :'label' => :'label',
        :'description' => :'description',
        :'required' => :'required',
        :'category' => :'category',
        :'question_type' => :'question_type',
        :'unified_key' => :'unified_key',
        :'options' => :'options',
        :'display_when' => :'display_when'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'block_type' => :'String',
        :'question_id' => :'String',
        :'label' => :'String',
        :'description' => :'String',
        :'required' => :'Boolean',
        :'category' => :'String',
        :'question_type' => :'String',
        :'unified_key' => :'String',
        :'options' => :'Array<PostAiApplyPostingsPostingIdInquirePositiveResponseDataApplicationFormInnerAnyOfOptionsInner>',
        :'display_when' => :'PostAiApplyPostingsPostingIdInquirePositiveResponseDataApplicationFormInnerAnyOfDisplayWhen'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'description',
        :'category',
        :'unified_key',
        :'options',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::PostAiApplyPostingsPostingIdInquirePositiveResponseDataApplicationFormInnerAnyOf` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::PostAiApplyPostingsPostingIdInquirePositiveResponseDataApplicationFormInnerAnyOf`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'block_type')
        self.block_type = attributes[:'block_type']
      else
        self.block_type = nil
      end

      if attributes.key?(:'question_id')
        self.question_id = attributes[:'question_id']
      else
        self.question_id = nil
      end

      if attributes.key?(:'label')
        self.label = attributes[:'label']
      else
        self.label = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      else
        self.description = nil
      end

      if attributes.key?(:'required')
        self.required = attributes[:'required']
      else
        self.required = nil
      end

      if attributes.key?(:'category')
        self.category = attributes[:'category']
      else
        self.category = nil
      end

      if attributes.key?(:'question_type')
        self.question_type = attributes[:'question_type']
      else
        self.question_type = nil
      end

      if attributes.key?(:'unified_key')
        self.unified_key = attributes[:'unified_key']
      else
        self.unified_key = nil
      end

      if attributes.key?(:'options')
        if (value = attributes[:'options']).is_a?(Array)
          self.options = value
        end
      else
        self.options = nil
      end

      if attributes.key?(:'display_when')
        self.display_when = attributes[:'display_when']
      else
        self.display_when = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @block_type.nil?
        invalid_properties.push('invalid value for "block_type", block_type cannot be nil.')
      end

      if @question_id.nil?
        invalid_properties.push('invalid value for "question_id", question_id cannot be nil.')
      end

      if @label.nil?
        invalid_properties.push('invalid value for "label", label cannot be nil.')
      end

      if @required.nil?
        invalid_properties.push('invalid value for "required", required cannot be nil.')
      end

      if @question_type.nil?
        invalid_properties.push('invalid value for "question_type", question_type cannot be nil.')
      end

      if @display_when.nil?
        invalid_properties.push('invalid value for "display_when", display_when cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @block_type.nil?
      block_type_validator = EnumAttributeValidator.new('String', ["QUESTION"])
      return false unless block_type_validator.valid?(@block_type)
      return false if @question_id.nil?
      return false if @label.nil?
      return false if @required.nil?
      category_validator = EnumAttributeValidator.new('String', ["EEO"])
      return false unless category_validator.valid?(@category)
      return false if @question_type.nil?
      question_type_validator = EnumAttributeValidator.new('String', ["TEXT", "NUMBER", "BOOLEAN", "FILE", "DATE", "SINGLE_SELECT", "MULTI_SELECT"])
      return false unless question_type_validator.valid?(@question_type)
      unified_key_validator = EnumAttributeValidator.new('String', ["EMAIL", "RESIDENCE_TYPE", "RESIDENCE_FULL_STRING", "RESIDENCE_COUNTRY", "RESIDENCE_CITY", "RESIDENCE_STATE", "RESIDENCE_LINE_1", "RESIDENCE_LINE_2", "RESIDENCE_ZIP_CODE", "APPLICANT_POOL_CONSENT", "TERMS_AND_CONDITIONS", "FIRST_NAME", "LAST_NAME", "FULL_NAME", "GENDER", "EXPECTED_START_DATE", "RESUME", "BIRTH_DATE", "PHONE_NUMBER_TYPE", "FULL_PHONE_NUMBER", "PHONE_COUNTRY_CODE", "PHONE_NATIONAL_NUMBER", "PHONE_EXTENSION"])
      return false unless unified_key_validator.valid?(@unified_key)
      return false if @display_when.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] block_type Object to be assigned
    def block_type=(block_type)
      validator = EnumAttributeValidator.new('String', ["QUESTION"])
      unless validator.valid?(block_type)
        fail ArgumentError, "invalid value for \"block_type\", must be one of #{validator.allowable_values}."
      end
      @block_type = block_type
    end

    # Custom attribute writer method with validation
    # @param [Object] question_id Value to be assigned
    def question_id=(question_id)
      if question_id.nil?
        fail ArgumentError, 'question_id cannot be nil'
      end

      @question_id = question_id
    end

    # Custom attribute writer method with validation
    # @param [Object] label Value to be assigned
    def label=(label)
      if label.nil?
        fail ArgumentError, 'label cannot be nil'
      end

      @label = label
    end

    # Custom attribute writer method with validation
    # @param [Object] required Value to be assigned
    def required=(required)
      if required.nil?
        fail ArgumentError, 'required cannot be nil'
      end

      @required = required
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] category Object to be assigned
    def category=(category)
      validator = EnumAttributeValidator.new('String', ["EEO"])
      unless validator.valid?(category)
        fail ArgumentError, "invalid value for \"category\", must be one of #{validator.allowable_values}."
      end
      @category = category
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] question_type Object to be assigned
    def question_type=(question_type)
      validator = EnumAttributeValidator.new('String', ["TEXT", "NUMBER", "BOOLEAN", "FILE", "DATE", "SINGLE_SELECT", "MULTI_SELECT"])
      unless validator.valid?(question_type)
        fail ArgumentError, "invalid value for \"question_type\", must be one of #{validator.allowable_values}."
      end
      @question_type = question_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] unified_key Object to be assigned
    def unified_key=(unified_key)
      validator = EnumAttributeValidator.new('String', ["EMAIL", "RESIDENCE_TYPE", "RESIDENCE_FULL_STRING", "RESIDENCE_COUNTRY", "RESIDENCE_CITY", "RESIDENCE_STATE", "RESIDENCE_LINE_1", "RESIDENCE_LINE_2", "RESIDENCE_ZIP_CODE", "APPLICANT_POOL_CONSENT", "TERMS_AND_CONDITIONS", "FIRST_NAME", "LAST_NAME", "FULL_NAME", "GENDER", "EXPECTED_START_DATE", "RESUME", "BIRTH_DATE", "PHONE_NUMBER_TYPE", "FULL_PHONE_NUMBER", "PHONE_COUNTRY_CODE", "PHONE_NATIONAL_NUMBER", "PHONE_EXTENSION"])
      unless validator.valid?(unified_key)
        fail ArgumentError, "invalid value for \"unified_key\", must be one of #{validator.allowable_values}."
      end
      @unified_key = unified_key
    end

    # Custom attribute writer method with validation
    # @param [Object] display_when Value to be assigned
    def display_when=(display_when)
      if display_when.nil?
        fail ArgumentError, 'display_when cannot be nil'
      end

      @display_when = display_when
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          block_type == o.block_type &&
          question_id == o.question_id &&
          label == o.label &&
          description == o.description &&
          required == o.required &&
          category == o.category &&
          question_type == o.question_type &&
          unified_key == o.unified_key &&
          options == o.options &&
          display_when == o.display_when
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [block_type, question_id, label, description, required, category, question_type, unified_key, options, display_when].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
