=begin
#Kombo API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module Kombo
  class SyncFinishedWebhookPayloadData < ApiModelBase
    # The unique identifier of the sync operation.
    attr_accessor :sync_id

    # The final state of the sync operation (e.g., `SUCCEEDED`, `FAILED`).
    attr_accessor :sync_state

    # ISO 8601 timestamp when the sync operation started.
    attr_accessor :sync_started_at

    # ISO 8601 timestamp when the sync operation completed.
    attr_accessor :sync_ended_at

    # Duration of the sync operation in seconds.
    attr_accessor :sync_duration_seconds

    # The unique identifier of the integration.
    attr_accessor :integration_id

    # The name of the integrated tool (e.g., \"personio\", \"greenhouse\").
    attr_accessor :integration_tool

    # The category of the integration (HRIS, ATS, or ASSESSMENT).
    attr_accessor :integration_category

    attr_accessor :end_user

    # URL to view detailed logs for the operation.
    attr_accessor :log_url

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'sync_id' => :'sync_id',
        :'sync_state' => :'sync_state',
        :'sync_started_at' => :'sync_started_at',
        :'sync_ended_at' => :'sync_ended_at',
        :'sync_duration_seconds' => :'sync_duration_seconds',
        :'integration_id' => :'integration_id',
        :'integration_tool' => :'integration_tool',
        :'integration_category' => :'integration_category',
        :'end_user' => :'end_user',
        :'log_url' => :'log_url'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'sync_id' => :'String',
        :'sync_state' => :'String',
        :'sync_started_at' => :'Time',
        :'sync_ended_at' => :'Time',
        :'sync_duration_seconds' => :'Integer',
        :'integration_id' => :'String',
        :'integration_tool' => :'String',
        :'integration_category' => :'String',
        :'end_user' => :'ConnectionFlowFailedWebhookPayloadDataEndUser',
        :'log_url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kombo::SyncFinishedWebhookPayloadData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kombo::SyncFinishedWebhookPayloadData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'sync_id')
        self.sync_id = attributes[:'sync_id']
      else
        self.sync_id = nil
      end

      if attributes.key?(:'sync_state')
        self.sync_state = attributes[:'sync_state']
      else
        self.sync_state = nil
      end

      if attributes.key?(:'sync_started_at')
        self.sync_started_at = attributes[:'sync_started_at']
      else
        self.sync_started_at = nil
      end

      if attributes.key?(:'sync_ended_at')
        self.sync_ended_at = attributes[:'sync_ended_at']
      else
        self.sync_ended_at = nil
      end

      if attributes.key?(:'sync_duration_seconds')
        self.sync_duration_seconds = attributes[:'sync_duration_seconds']
      else
        self.sync_duration_seconds = nil
      end

      if attributes.key?(:'integration_id')
        self.integration_id = attributes[:'integration_id']
      else
        self.integration_id = nil
      end

      if attributes.key?(:'integration_tool')
        self.integration_tool = attributes[:'integration_tool']
      else
        self.integration_tool = nil
      end

      if attributes.key?(:'integration_category')
        self.integration_category = attributes[:'integration_category']
      else
        self.integration_category = nil
      end

      if attributes.key?(:'end_user')
        self.end_user = attributes[:'end_user']
      else
        self.end_user = nil
      end

      if attributes.key?(:'log_url')
        self.log_url = attributes[:'log_url']
      else
        self.log_url = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @sync_id.nil?
        invalid_properties.push('invalid value for "sync_id", sync_id cannot be nil.')
      end

      if @sync_state.nil?
        invalid_properties.push('invalid value for "sync_state", sync_state cannot be nil.')
      end

      if @sync_started_at.nil?
        invalid_properties.push('invalid value for "sync_started_at", sync_started_at cannot be nil.')
      end

      if @sync_ended_at.nil?
        invalid_properties.push('invalid value for "sync_ended_at", sync_ended_at cannot be nil.')
      end

      if @sync_duration_seconds.nil?
        invalid_properties.push('invalid value for "sync_duration_seconds", sync_duration_seconds cannot be nil.')
      end

      if @sync_duration_seconds < 0
        invalid_properties.push('invalid value for "sync_duration_seconds", must be greater than or equal to 0.')
      end

      if @integration_id.nil?
        invalid_properties.push('invalid value for "integration_id", integration_id cannot be nil.')
      end

      if @integration_tool.nil?
        invalid_properties.push('invalid value for "integration_tool", integration_tool cannot be nil.')
      end

      if @integration_category.nil?
        invalid_properties.push('invalid value for "integration_category", integration_category cannot be nil.')
      end

      if @end_user.nil?
        invalid_properties.push('invalid value for "end_user", end_user cannot be nil.')
      end

      if @log_url.nil?
        invalid_properties.push('invalid value for "log_url", log_url cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @sync_id.nil?
      return false if @sync_state.nil?
      return false if @sync_started_at.nil?
      return false if @sync_ended_at.nil?
      return false if @sync_duration_seconds.nil?
      return false if @sync_duration_seconds < 0
      return false if @integration_id.nil?
      return false if @integration_tool.nil?
      return false if @integration_category.nil?
      integration_category_validator = EnumAttributeValidator.new('String', ["HRIS", "ATS", "ASSESSMENT"])
      return false unless integration_category_validator.valid?(@integration_category)
      return false if @end_user.nil?
      return false if @log_url.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] sync_id Value to be assigned
    def sync_id=(sync_id)
      if sync_id.nil?
        fail ArgumentError, 'sync_id cannot be nil'
      end

      @sync_id = sync_id
    end

    # Custom attribute writer method with validation
    # @param [Object] sync_state Value to be assigned
    def sync_state=(sync_state)
      if sync_state.nil?
        fail ArgumentError, 'sync_state cannot be nil'
      end

      @sync_state = sync_state
    end

    # Custom attribute writer method with validation
    # @param [Object] sync_started_at Value to be assigned
    def sync_started_at=(sync_started_at)
      if sync_started_at.nil?
        fail ArgumentError, 'sync_started_at cannot be nil'
      end

      @sync_started_at = sync_started_at
    end

    # Custom attribute writer method with validation
    # @param [Object] sync_ended_at Value to be assigned
    def sync_ended_at=(sync_ended_at)
      if sync_ended_at.nil?
        fail ArgumentError, 'sync_ended_at cannot be nil'
      end

      @sync_ended_at = sync_ended_at
    end

    # Custom attribute writer method with validation
    # @param [Object] sync_duration_seconds Value to be assigned
    def sync_duration_seconds=(sync_duration_seconds)
      if sync_duration_seconds.nil?
        fail ArgumentError, 'sync_duration_seconds cannot be nil'
      end

      if sync_duration_seconds < 0
        fail ArgumentError, 'invalid value for "sync_duration_seconds", must be greater than or equal to 0.'
      end

      @sync_duration_seconds = sync_duration_seconds
    end

    # Custom attribute writer method with validation
    # @param [Object] integration_id Value to be assigned
    def integration_id=(integration_id)
      if integration_id.nil?
        fail ArgumentError, 'integration_id cannot be nil'
      end

      @integration_id = integration_id
    end

    # Custom attribute writer method with validation
    # @param [Object] integration_tool Value to be assigned
    def integration_tool=(integration_tool)
      if integration_tool.nil?
        fail ArgumentError, 'integration_tool cannot be nil'
      end

      @integration_tool = integration_tool
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] integration_category Object to be assigned
    def integration_category=(integration_category)
      validator = EnumAttributeValidator.new('String', ["HRIS", "ATS", "ASSESSMENT"])
      unless validator.valid?(integration_category)
        fail ArgumentError, "invalid value for \"integration_category\", must be one of #{validator.allowable_values}."
      end
      @integration_category = integration_category
    end

    # Custom attribute writer method with validation
    # @param [Object] end_user Value to be assigned
    def end_user=(end_user)
      if end_user.nil?
        fail ArgumentError, 'end_user cannot be nil'
      end

      @end_user = end_user
    end

    # Custom attribute writer method with validation
    # @param [Object] log_url Value to be assigned
    def log_url=(log_url)
      if log_url.nil?
        fail ArgumentError, 'log_url cannot be nil'
      end

      @log_url = log_url
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          sync_id == o.sync_id &&
          sync_state == o.sync_state &&
          sync_started_at == o.sync_started_at &&
          sync_ended_at == o.sync_ended_at &&
          sync_duration_seconds == o.sync_duration_seconds &&
          integration_id == o.integration_id &&
          integration_tool == o.integration_tool &&
          integration_category == o.integration_category &&
          end_user == o.end_user &&
          log_url == o.log_url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [sync_id, sync_state, sync_started_at, sync_ended_at, sync_duration_seconds, integration_id, integration_tool, integration_category, end_user, log_url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
